### ISSUE TITLE
Old casks should not completely break homebrew

### ISSUE THREAD

**Issue by cpcallen** [Homebrew/homebrew-cask#90835] opened 2020-10-14 09:01 UTC
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Certain old casks apparently depend on an `undent` method that has been removed from `homebrew-cask`.  This causes Homebrew to be more or less completely broken; even `brew doctor` fails.  This has happened over and over again to different users (#49716, #50707, #50727, #50999, #55721, #57957, #59117, #63117, #86997, #87269, #88501, #89543, #90224, #90322, Homebrew/brew#4494, Homebrew/brew#8756).

A package manager like homebrew ought to be able to uninstall any package it previously installed, no matter how long ago, and a broken or outdated package should not break the package manager itself—and certainly not the break-diagnostic function.

I actually regard this as a bug in `brew`, but it was already reported there (Homebrew/brew#8756) and @MikeMcQuaid closed it as a "known issue on Cask side"—yet there is no open bug about it here, so I am opening this one.

Please note that this is not a request for assistance fixing my own install; it is a request that homebrew maintain backward compatibility with its own installations.

#### Command that failed

```
$ brew doctor
Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007fe7908adb88>
```

#### Output of command with `--force --verbose --debug`

```
$ brew doctor --force --verbose --debug
Usage: brew doctor [options]

Check your system for potential problems. Will exit with a non-zero status if
any potential problems are found. Please note that these warnings are just used
to help the Homebrew maintainers with debugging if you file an issue. If
everything you use Homebrew for is working fine: please don't worry or file an
issue; just ignore this.

      --list-checks                List all audit methods, which can be run
                                   individually if provided as arguments.
  -D, --audit-debug                Enable debugging and profiling of audit
                                   methods.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Suppress any warnings.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.
Error: invalid option: --force
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:238:in `parse_remaining'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:288:in `parse'
/usr/local/Homebrew/Library/Homebrew/compat/cli/parser.rb:23:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:31:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'
```

#### Output of `brew doctor --verbose`

```
$ brew doctor --verbose
Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007f8ba912b1a0>
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/cask-versions
homebrew/core
jichu4n/palm-os
```

**Comment by reitermarkus** [comment] 2020-10-14 09:08
Can you also post the output of `brew doctor --verbose --debug`?

**Comment by cpcallen** [comment] 2020-10-14 09:34
> Can you also post the output of `brew doctor --verbose --debug`?

Sorry; I have sorted the problem by removing the offending cask.  I'm sure another user will have the problem soon, though!

**Comment by cpcallen** [comment] 2020-10-14 09:36
Ahh, I was able to restore the broken cask using Time Machine.  Here you go:

```
$ brew doctor --verbose --debug
Error: Cask 'java' is unreadable: undefined method `undent' for #<String:0x00007fb2ee10d7b0>
/usr/local/Caskroom/java/.metadata/1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441/20170228041514.319/Casks/java.rb:82:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:59:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:59:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:46:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/java/.metadata/1.8.0_121-b13,e9e7ea248e2c4826b92b3f075a80e441/20170228041514.319/Casks/java.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:42:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:36:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:36:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:48:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:120:in `<main>'
```

**Comment by MikeMcQuaid** [comment] 2020-10-14 10:34
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/90835 and https://github.com/Homebrew/homebrew-cask/issues/62223 and https://github.com/Homebrew/homebrew-cask/issues/83178. Please don't open the same issue in multiple places, thanks.

**Comment by MikeMcQuaid** [comment] 2020-10-14 10:35
> Please don't open the same issue in multiple places, thanks.

My apologies, I got confused by the issue being transfer across the repositories 🙇🏻

**Closed by MikeMcQuaid** 2020-10-14 10:34 UTC

**Comment by cpcallen** [comment] 2020-10-14 11:06
I'm amused that you've closed this bug as duplicate of itself!  Thanks for pointing out #62223; I did not find that while looking for bugs about this problem.
