### ISSUE TITLE
Bad CPU type in executable While Installing XAMPP Cask

### ISSUE THREAD

**Issue by bobdownsnet** [Homebrew/homebrew-cask#72044] opened 2019-11-05 01:12 UTC
#### General troubleshooting steps

- [ x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ x] I have retried my command with `--force`.
- [ x] I ran `brew update-reset && brew update` and retried my command.
- [ x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [ x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [ x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When I run "brew cask install xampp" in iTerm (zsh), I get the following error:
==> Purging files for version 7.3.4-0 of Cask xampp
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/xampp/7.3.4-0/XAMPP.app/Contents/MacOS/osx-intel --mode unattended` exited with 126. Here's the output:
env: /usr/local/Caskroom/xampp/7.3.4-0/XAMPP.app/Contents/MacOS/osx-intel: Bad CPU type in executable

#### Command that failed

```
brew cask install xampp
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://downloadsapachefriends.global.ssl.fastly.net/xampp-files/7.3.4/xampp-osx-7.3.4-0-installer.dmg
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.15-118-gc169348\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.1\)\ curl/7.64.1 --location --silent --head --request GET https://downloadsapachefriends.global.ssl.fastly.net/xampp-files/7.3.4/xampp-osx-7.3.4-0-installer.dmg
Already downloaded: /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
==> /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg is quarantined
==> Downloaded to -> /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
==> Verifying SHA-256 checksum for Cask 'xampp'.
hdiutil imageinfo -format /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
==> Installing Cask xampp
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/d20191104-88737-bxfiiq /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
find . -print0
mkbom -s -i /var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/20191104-88737-dr12jh.list -- /var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/20191104-88737-b5qzf1.bom
ditto --bom /var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/20191104-88737-b5qzf1.bom -- /private/var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/d20191104-88737-bxfiiq/dmg.yErxb2 /var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/d20191104-88737-14gjbhp
diskutil eject /private/var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/d20191104-88737-bxfiiq/dmg.yErxb2
cp -pR /var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/d20191104-88737-14gjbhp/XAMPP.app/. /usr/local/Caskroom/xampp/7.3.4-0/XAMPP.app
chmod -Rf +w /var/folders/gg/22r57z_913sfzd3vqqz23c5c0000gn/T/d20191104-88737-14gjbhp
==> Verifying Gatekeeper status of /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
==> /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg is quarantined
==> Propagating quarantine from /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg to /usr/local/Caskroom/xampp/7.3.4-0
/usr/bin/xattr -p com.apple.quarantine /Users/bobhome/Library/Caches/Homebrew/downloads/56829d0cfa746fbbab6bc57f712d4b55aca8f793aaa434a791d2ed30b82e6fbc--xampp-osx-7.3.4-0-installer.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5dc0c9b8\;Homebrew\\x20Cask\;DA0BF08F-5ACF-4F2C-B9EF-97B6F98C6110
==> Creating metadata directory /usr/local/Caskroom/xampp/.metadata/7.3.4-0/20191105010655.372.
==> Creating metadata subdirectory /usr/local/Caskroom/xampp/.metadata/7.3.4-0/20191105010655.372/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007ff33ca95e98 @cask=#<Cask::Cask:0x00007ff33c97aab8 @token="xampp", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/xampp.rb>, @tap=#<Tap:0x00007ff33c9639a8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007ff33c97aa18@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/xampp.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/xampp>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/xampp/.metadata>, @config=#<Cask::Config:0x00007ff33ca88478 @explicit={}>, @dsl=#<Cask::DSL:0x00007ff33ca88180 @cask=#<Cask::Cask:0x00007ff33c97aab8 ...>, @token="xampp", @version="7.3.4-0", @sha256="d75688bbfaa943e293218fe4546d9ff3d104f89b99815b2fe3ec179545b5188c", @url=#<URL:0x00007ff33ca973b0 @uri=#<URI::HTTPS https://downloadsapachefriends.global.ssl.fastly.net/xampp-files/7.3.4/xampp-osx-7.3.4-0-installer.dmg>, @user_agent=:default, @specs={}>, @name=["XAMPP"], @homepage="https://www.apachefriends.org/index.html", @artifacts=#<SortedSet: {...}>, @language=nil>>, @directives={:quit=>"com.bitnami.manager", :script=>{:executable=>"/Applications/XAMPP/uninstall.app/Contents/MacOS/osx-intel", :args=>["--mode", "unattended"], :sudo=>true}, :delete=>"/Applications/XAMPP/", :signal=>[]}>, #<Cask::Artifact::Installer:0x00007ff33ca96730 @cask=#<Cask::Cask:0x00007ff33c97aab8 @token="xampp", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/xampp.rb>, @tap=#<Tap:0x00007ff33c9639a8 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007ff33c97aa18@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/xampp.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/xampp>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/xampp/.metadata>, @config=#<Cask::Config:0x00007ff33ca88478 @explicit={}>, @dsl=#<Cask::DSL:0x00007ff33ca88180 @cask=#<Cask::Cask:0x00007ff33c97aab8 ...>, @token="xampp", @version="7.3.4-0", @sha256="d75688bbfaa943e293218fe4546d9ff3d104f89b99815b2fe3ec179545b5188c", @url=#<URL:0x00007ff33ca973b0 @uri=#<URI::HTTPS https://downloadsapachefriends.global.ssl.fastly.net/xampp-files/7.3.4/xampp-osx-7.3.4-0-installer.dmg>, @user_agent=:default, @specs={}>, @name=["XAMPP"], @homepage="https://www.apachefriends.org/index.html", @artifacts=#<SortedSet: {...}>, @language=nil>>, @args={:must_succeed=>true, :sudo=>true, :args=>["--mode", "unattended"], :print_stdout=>true}, @path=#<Pathname:XAMPP.app/Contents/MacOS/osx-intel>>}>
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script 'XAMPP.app/Contents/MacOS/osx-intel'
/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/xampp/7.3.4-0/XAMPP.app/Contents/MacOS/osx-intel --mode unattended
env: /usr/local/Caskroom/xampp/7.3.4-0/XAMPP.app/Contents/MacOS/osx-intel: Bad CPU type in executable
==> Purging files for version 7.3.4-0 of Cask xampp
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/xampp/7.3.4-0/XAMPP.app/Contents/MacOS/osx-intel --mode unattended` exited with 126. Here's the output:
env: /usr/local/Caskroom/xampp/7.3.4-0/XAMPP.app/Contents/MacOS/osx-intel: Bad CPU type in executable

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:220:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:211:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:103:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:167:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.15-118-gc169348
==> macOS
10.15.1
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3499 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by reitermarkus** [comment] 2019-11-05 03:55
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/71798.

**Closed by reitermarkus** 2019-11-05 03:55 UTC
