### ISSUE TITLE
install openvpn-connect make Mac cannot shutdown.

### ISSUE THREAD

**Issue by yiheng233** [Homebrew/homebrew-cask#85671] opened 2020-07-10 05:45 UTC
#### General troubleshooting steps

- [yes] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [no] I have retried my command with `--force`.
- [yes] I ran `brew update-reset && brew update` and retried my command.
- [yes] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [yes] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [yes] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

install openvpn-connect has finished but the Mac can't shutdown.

#### Command that failed

```
brew cask upgrade
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 1 outdated package:
openvpn-connect 3.2.0,1426 -> 3.2.1,1484
==> Upgrading openvpn-connect
==> Downloading https://swupdate.openvpn.net/downloads/connect/openvpn-connect-3.2.1.1484_signed.dmg
Already downloaded: /Users/yihengzhaotext/Library/Caches/Homebrew/downloads/40a9d8e8a4950b3ff58c4eb9b4a7e3d7d0b160ac78d20916e7e21637727e832f--openvpn-connect-3.2.1.1484_signed.dmg
==> Verifying SHA-256 checksum for Cask 'openvpn-connect'.
==> Removing launchctl service org.openvpn.client
Password:
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.4.5
==> macOS
10.15.6
==> SIP
Enabled
==> Java
14.0.1
==> xattr issues
<NONE>
==> Gatekeeper support
Error: Unknown support status
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3607 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.41.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by miccal** [comment] 2020-07-10 06:56
```
Password:
```
Did you enter your password as requested here?

**Comment by yiheng233** [comment] 2020-07-10 09:08
yes

**Comment by yiheng233** [comment] 2020-07-10 09:11
I meet this problem when I install any package request password .(such as google-earth-pro and virualbox)

**Comment by yiheng233** [comment] 2020-07-10 09:14
I didn't enter password here, this is a show because when it finished the installation the macOS became damaged.

**Comment by yiheng233** [comment] 2020-07-10 09:15
this is a backup

**Comment by miccal** [comment] 2020-07-10 10:09
So, if I understand correctly you enter your password and then nothing happens?

**Comment by yiheng233** [comment] 2020-07-10 10:11
no, the brew say the app has been installed successfully, but when I reboot the system can't shutdown.

**Comment by miccal** [comment] 2020-07-10 10:20
Why do you think that your shutdown issue has anything to do with `brew` or `brew cask`? Shutdown problems are a common issue with Catalina, I think because of the presence of `kext`'s that will be deprecated in the next version of macOS.

**Comment by yiheng233** [comment] 2020-07-10 10:28
Because I run brew cask then it can't shutdown ,I made a time machine before I run brew cask then I restored the backup then I can shutdown again.(In other words, before I run brew cask the macOS can shutdown but when I run brew cask(which requests password) it can't .)

**Comment by vitorgalvao** [comment] 2020-07-10 11:39
Please don’t treat issues like a chat program. Four replies in a row isn’t acceptable. You’re asking us for help, it should be in your interest to make it easy for us.

Tip: use `x` in checklists (no spaces inside the brackets) and [Github will make them clickable](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments).

No one else is having this issue, and we don’t do anything to prevent shutdowns. The issue is either on your side (extremely likely) or we need exact reproduction steps that can work on other machines.

Closing.

**Closed** 2020-07-10 11:49 UTC
