### ISSUE TITLE
Dock icons are removed on upgrading casks

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/homebrew-cask#107599] opened 2021-06-23 06:35 UTC
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

I hesitate to call this a bug, but it is certainly a misfeature. The issue is as follows: for several of the apps I have installed from casks, I have dragged the app's icon to the dock so I can readily launch it. Unfortunately, when I upgrade such an app, the dock icon is removed, and I have to manually re-add it after doing the upgrade. While this is not a serious problem, it would be more helpful to users if this removal did not occur. 

Examples of apps that I recently have had this problem with are keka, and graphicconverter.  

I may be wrong, but it seems that the strategy for upgrading casks is essentially remove app, and install again. Removal leads to the dock icon also being removed. Would it be possible to implement a strategy to reinstate the original dock settings after reinstallation? 

### Command that failed

brew upgrade (some app)

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

(Not relevant, as upgrade worked as expected / intended except as described above)

</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>

(Ditto)

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

(Ditto)

</code></pre></details>

**Comment by ralphrmartin** [comment] 2021-06-23 06:42
Perhaps I should add that this is on MacOS 11.4, in case any recent changes to MacOS have affected dock behaviour.

**Comment by cho-m** [comment] 2021-06-23 06:44
Closing as duplicate of a known issue #102721
There is some discussion of a potential solution over there.

At this point in time, we mainly need someone to work on the issue and submit a PR.

**Closed by cho-m** 2021-06-23 06:44 UTC
