### ISSUE TITLE
"is brew cask had problem with FileVault on MBP 2018"#51824 further information provided

### ISSUE THREAD

**Issue by NonoXie** [Homebrew/homebrew-cask#52116] opened 2018-09-18 02:03 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
-----
Since I got my new MBP 2018 last week and start using brew cask to install some app I need.
I noticed some app states that they're not in a place they can do r/w operation, so they terminated themself(ex. adguard, sourcetree, box-sync...) or asking me to put them(ex. bettertouchtool) back into /Appliation which they already are!

Today I turn off FileVault, and seems all the problems are vanished.
------
It happened again with FileVault on or not(tested).

#### Command that failed

```
brew cask install adguard
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://static.adguard.com/mac/Adguard-1.5.8.release.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://static.adguard.com/mac/Adguard-1.5.8.release.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://static.adguard.com/mac/Adguard-1.5.8.release.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg.incomplete https://static.adguard.com/mac/Adguard-1.5.8.release.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43.1M  100 43.1M    0     0  3071k      0  0:00:14  0:00:14 --:--:-- 2632k
==> Checking quarantine support
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
==> /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg is not quarantined
==> Quarantining /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg https://static.adguard.com/mac/Adguard-1.5.8.release.dmg https://adguard.com/
==> Downloaded to -> /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
==> Verifying SHA-256 checksum for Cask 'adguard'.
==> Installing Cask adguard
==> Cask::Installer#stage
hdiutil imageinfo /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/dp/h6sw_jn50t19tppw194c02th0000gn/T/d20180918-23413-18xrpw0 /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
find . -print0
mkbom -s -i /var/folders/dp/h6sw_jn50t19tppw194c02th0000gn/T/20180918-23413-14rqpdh.list -- /var/folders/dp/h6sw_jn50t19tppw194c02th0000gn/T/20180918-23413-1gx7hk5.bom
ditto --bom /var/folders/dp/h6sw_jn50t19tppw194c02th0000gn/T/20180918-23413-1gx7hk5.bom -- /private/var/folders/dp/h6sw_jn50t19tppw194c02th0000gn/T/d20180918-23413-18xrpw0/dmg.N4AeCk /var/folders/dp/h6sw_jn50t19tppw194c02th0000gn/T/d20180918-23413-2bckzk
diskutil eject /private/var/folders/dp/h6sw_jn50t19tppw194c02th0000gn/T/d20180918-23413-18xrpw0/dmg.N4AeCk
cp -pR /var/folders/dp/h6sw_jn50t19tppw194c02th0000gn/T/d20180918-23413-2bckzk/Adguard.app/. /usr/local/Caskroom/adguard/1.5.8/Adguard.app
==> Verifying Gatekeeper status of /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
==> /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg is quarantined
==> Propagating quarantine from /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg to /usr/local/Caskroom/adguard/1.5.8
/usr/bin/xattr -p com.apple.quarantine /Users/normanxie/Library/Caches/Homebrew/downloads/15c3f86a65c7e66be67dd257091b53125ad61b589c50b9e1e0168ef08605a80e--Adguard-1.5.8.release.dmg
/bin/chmod -R u\+w /usr/local/Caskroom/adguard/1.5.8
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5ba05a69\;Homebrew\\x20Cask\;9C69504C-2828-47AE-BC3F-8BA4015E53E2
==> Creating metadata directory /usr/local/Caskroom/adguard/.metadata/1.5.8/20180918015248.420.
==> Creating metadata subdirectory /usr/local/Caskroom/adguard/.metadata/1.5.8/20180918015248.420/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007ff5adaf7f30>
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Adguard.app' to '/Applications/Adguard.app'.
🍺  adguard was successfully installed!
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.5
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2-zulu-10.3+5, 10.0.2, 9.0.0-zulu-9.0.7.1, 1.8.0_181-zulu-8.31.0.1, 1.8.0_181, 1.7.0_181-zulu-7.23.0.1, 1.6.0_65-b14-468
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4041 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
vitorgalvao/tiny-scripts
```

**Comment by amyspark** [comment] 2018-09-19 00:43
Duplicate of #51663, fixed in Homebrew/brew#4852.

As I see you're running a stable version of Homebrew, please issue:
```
cd $(brew --repo); git checkout master; git pull
```
to get the fixes ASAP.

**Closed** 2018-09-19 00:43 UTC
