### ISSUE TITLE
Sourcetree SHA256 Actually Incorrect

### ISSUE THREAD

**Issue by DevinWatson** [Homebrew/homebrew-cask#51098] opened 2018-08-21 20:39 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

It looks like the Sourcetree [sha256](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sourcetree.rb#L3) is actually incorrect. 

Expected: d60614e9ab603e0ed158b6473c36e7944b2908d9943e332c505eba03dc1d829e
Actual: 43ae71d44718177ca0584b7aac94022d57d862b14584b474f997bec8ea7b374a

```
curl -s https://downloads.atlassian.com/software/sourcetree/Sourcetree_2.7.6a.zip|openssl sha -sha256
43ae71d44718177ca0584b7aac94022d57d862b14584b474f997bec8ea7b374a
```

#### Command that failed

```
brew cask install sourcetree
```

#### Output of command with `--force --verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.atlassian.com/software/sourcetree/Sourcetree_2.7.6a.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.2-4-g713532e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --silent --head --write-out \%\{redirect_url\} --output /dev/null https://downloads.atlassian.com/software/sourcetree/Sourcetree_2.7.6a.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.2-4-g713532e\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/user/Library/Caches/Homebrew/Cask/sourcetree--2.7.6a.zip.incomplete https://downloads.atlassian.com/software/sourcetree/Sourcetree_2.7.6a.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 65.2M    0 65.2M    0     0  3994k      0 --:--:--  0:00:16 --:--:-- 4932k
==> Downloaded to -> /Users/user/Library/Caches/Homebrew/Cask/sourcetree--2.7.6a.zip
==> Verifying download
==> Determining which verifications to run for Cask sourcetree
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask sourcetree
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'sourcetree' does not match.

Expected: d60614e9ab603e0ed158b6473c36e7944b2908d9943e332c505eba03dc1d829e
Actual:   43ae71d44718177ca0584b7aac94022d57d862b14584b474f997bec8ea7b374a
File:     /Users/user/Library/Caches/Homebrew/Cask/sourcetree--2.7.6a.zip

To retry an incomplete download, remove the file above.

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:42:in `verify_checksum'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify/checksum.rb:22:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:21:in `block in all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/verify.rb:19:in `all'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:152:in `verify'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:58:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.7.2-4-g713532e
Homebrew/homebrew-cask (git revision 8b6403; last commit 2018-08-21)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4029 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
git-duet/tap
homebrew/cask
homebrew/core
homebrew/services
pivotal/tap
```

**Comment by vitorgalvao** [comment] 2018-08-22 14:27
> - [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.

> It looks like the Sourcetree [sha256](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sourcetree.rb#L3) is actually incorrect. 
>
> Expected: d60614e9ab603e0ed158b6473c36e7944b2908d9943e332c505eba03dc1d829e
> Actual: 43ae71d44718177ca0584b7aac94022d57d862b14584b474f997bec8ea7b374a

---

Please help me understand this. What happened? Have you checked the box without reading it? Have you not understood the instructions? Something else (what)?

**Comment by vitorgalvao** [comment] 2018-08-22 14:35
> - [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.

> It looks like the Sourcetree [sha256](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sourcetree.rb#L3) is actually incorrect. 
>
> Expected: d60614e9ab603e0ed158b6473c36e7944b2908d9943e332c505eba03dc1d829e
> Actual: 43ae71d44718177ca0584b7aac94022d57d862b14584b474f997bec8ea7b374a

---

Please help me understand this. What happened? Have you checked the box without reading it? Have you not understood the instructions? Something else (what)? I want to understand so I can make it clearer.

Also, I can’t reproduce this at all. My download with the “Expected” sha256, so this looks like something on your end.

**Comment by micdah** [comment] 2018-08-29 18:40
@DevinWatson Just tried downloading and doing a sha256 of the file in question, using your suggested means using `curl` and `openssl` - I got the same sha256 as in the cask.

**Comment by vitorgalvao** [comment] 2018-08-29 19:55
@micdah That does not answer my question. The “I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.” checkbox has linked instructions that teach how to fix this. Did you at least click through and try to follow them?

**Comment by micdah** [comment] 2018-08-29 19:56
@vitorgalvao I didn't submit this issue, just tried to engage the author and chime in that I also *cannot* reproduce the error as submitted. 😄

**Comment by vitorgalvao** [comment] 2018-08-29 19:59
@micdah Oh, you’re right!

Well, considering the lack of reply and unreproduceability, I’m going to go ahead and close this.

**Closed by vitorgalvao** 2018-08-29 19:59 UTC
Labels: awaiting user reply
