### ISSUE TITLE
Please update IntelliJ IDEA to the latest version 2024.2.0.1, thank you

### ISSUE THREAD

**Issue by zhangyulai** [Homebrew/homebrew-cask#182564] opened 2024-08-15 23:35 UTC
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

"IntelliJ IDEA has been updated to version 2024.2.0.1. I wanted to submit a PR for the update, but I was informed that it would update automatically. However, the automatic update did not occur."
<img width="729" alt="iShot_2024-08-16_07 29 53" src="https://github.com/user-attachments/assets/e7ffa4b1-6f81-40fe-9457-bf94dc7ed1d8">
<img width="974" alt="iShot_2024-08-16_07 34 49" src="https://github.com/user-attachments/assets/1b474c95-9e11-4db1-a221-e72d3f3c1583">

### Command that failed

brew bump-cask-pr --version 2024.2.0.1,242.20224.387 intellij-idea

### Output of command with `--verbose --debug`

```shell
Fetching gem metadata from https://rubygems.org/.......
Fetching sorbet-runtime 0.5.11520
Installing sorbet-runtime 0.5.11520
Bundle complete! 38 Gemfile dependencies, 28 gems now installed.
Bundled gems are installed into `../../usr/local/Homebrew/Library/Homebrew/vendor/bundle`
Error: Whoops, the intellij-idea cask has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that's not in the autobump list:
  https://github.com/Homebrew/homebrew-cask/blob/master/.github/autobump.txt
```

### Output of `brew doctor` and `brew config`

```shell
Fetching gem metadata from https://rubygems.org/.......
Fetching sorbet-runtime 0.5.11520
Installing sorbet-runtime 0.5.11520
Bundle complete! 38 Gemfile dependencies, 28 gems now installed.
Bundled gems are installed into `../../usr/local/Homebrew/Library/Homebrew/vendor/bundle`
Error: Whoops, the intellij-idea cask has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that's not in the autobump list:
  https://github.com/Homebrew/homebrew-cask/blob/master/.github/autobump.txt
```

### Output of `brew tap`

```shell
Fetching gem metadata from https://rubygems.org/.......
Fetching sorbet-runtime 0.5.11520
Installing sorbet-runtime 0.5.11520
Bundle complete! 38 Gemfile dependencies, 28 gems now installed.
Bundled gems are installed into `../../usr/local/Homebrew/Library/Homebrew/vendor/bundle`
Error: Whoops, the intellij-idea cask has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that's not in the autobump list:
  https://github.com/Homebrew/homebrew-cask/blob/master/.github/autobump.txt
```

**Comment by ianrobrien** [comment] 2024-08-16 13:06
Looks like there's an issue with the [autobump](https://github.com/Homebrew/homebrew-cask/actions/runs/10417806951/job/28852740179):

> ==> intellij-idea
> Current cask version:     2024.2,242.20224.300
> Latest livecheck version: unable to get versions
> Open pull requests:       none
> Closed pull requests:     none

**Comment by SMillerDev** [comment] 2024-08-16 13:21
Does `brew livecheck intellij-idea` work locally?

**Comment by zhangyulai** [comment] 2024-08-16 13:52
> Does `brew livecheck intellij-idea` work locally?

➜  ~ brew livecheck intellij-idea
intellij-idea: 2024.2,242.20224.300 ==> 2024.2.0.1,242.20224.387

**Comment by zhangyulai** [comment] 2024-08-16 13:53
> Does `brew livecheck intellij-idea` work locally?

➜  ~ brew livecheck intellij-idea
intellij-idea: 2024.2,242.20224.300 ==> 2024.2.0.1,242.20224.387
<img width="480" alt="iShot_2024-08-16_21 52 50" src="https://github.com/user-attachments/assets/5eff8593-92a0-4ec7-82e6-3d9f6a6bcc7a">

**Comment by riggzh** [comment] 2024-08-18 18:31
+1

**Comment by ianrobrien** [comment] 2024-08-19 04:34
Same. So the version check works locally but not from the GitHub Actions runner. I'm assuming `brew livecheck` uses the same routine as the update workflow.

In that case, what could be the issue? Can the job run with debug output? Maybe there's a connectivity issue.

**Comment by SMillerDev** [comment] 2024-08-19 08:11
Could be that Jetbrains blocks requests from GitHub actions, it's hard to tell. You can always manually edit the file and make a pull request with that change though.

**Comment by viazovskyi585** [comment] 2024-08-19 08:20
I noticed that [alex313031-thorium](https://formulae.brew.sh/cask/alex313031-thorium) is not updated despite it is in autobump list too. Could this issue be more global?

**Comment by SMillerDev** [comment] 2024-08-19 08:27
> I noticed that [alex313031-thorium](https://formulae.brew.sh/cask/alex313031-thorium) is not updated despite it is in autobump list too. Could this issue be more global?

We don't really know what the issue is beyond "it works locally but not in CI", so it's hard to tell.

**Comment by viazovskyi585** [comment] 2024-08-19 08:42
@khipp thanks for the explanation 👍

**Comment by khipp** [comment] 2024-08-20 16:23
Closing this since the last automated version bump ran without issues: https://github.com/Homebrew/homebrew-cask/pull/182938.

**Closed by khipp** 2024-08-20 16:23 UTC
