### ISSUE TITLE
GitKraken - unidentified developer only via brew cask

### ISSUE THREAD

**Issue by lantrix** [Homebrew/homebrew-cask#54072] opened 2018-10-24 01:19 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When I download [gitkraken](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/gitkraken.rb) from their site the app is signed by the developer, and Mac OS X (10.13) verifies the app and allows me to open it if I approve.

<img width="482" alt="screenshot 2018-10-24 10 22 21" src="https://user-images.githubusercontent.com/117008/47396538-f4ebb180-d776-11e8-878f-c43cd0422aca.png">

When I download the SAME app via cask it gives me the known "[The app can’t be opened because it is from an unidentified developer](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/the_app_cant_be_opened.md)". I can use the workaround to launch it, however part of the brew cask install process seems to invalidate the validation process. In this case the developer IS identified with apple, the app is code signed, so this should not be occurring.

<img width="422" alt="screenshot 2018-10-24 12 18 11" src="https://user-images.githubusercontent.com/117008/47399983-e907eb80-d786-11e8-9d15-44416eef0103.png">

#### Command that failed

```
==> Satisfying dependencies
==> Downloading https://release.gitkraken.com/darwin/GitKraken-v4.0.6.zip
Already downloaded: /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
==> Verifying SHA-256 checksum for Cask 'gitkraken'.
==> Installing Cask gitkraken
==> Moving App 'GitKraken.app' to '/Applications/GitKraken.app'.
🍺  gitkraken was successfully installed!
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://release.gitkraken.com/darwin/GitKraken-v4.0.6.zip
Already downloaded: /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
/usr/bin/xattr -p com.apple.quarantine /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
==> /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip is quarantined
==> Downloaded to -> /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
==> Verifying SHA-256 checksum for Cask 'gitkraken'.
==> Installing Cask gitkraken
==> Cask::Installer#stage
zipinfo -1 /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
==> Extracting primary container
==> Using container class UnpackStrategy::Zip for /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
unzip /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip -d /var/folders/qj/th97jfws0v3flzwcy6ds5qmmy7_14y/T/d20181024-6324-eaziex
cp -pR /var/folders/qj/th97jfws0v3flzwcy6ds5qmmy7_14y/T/d20181024-6324-eaziex/GitKraken.app/. /usr/local/Caskroom/gitkraken/4.0.6/GitKraken.app
chmod -Rf +w /var/folders/qj/th97jfws0v3flzwcy6ds5qmmy7_14y/T/d20181024-6324-eaziex
==> Verifying Gatekeeper status of /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
/usr/bin/xattr -p com.apple.quarantine /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
==> /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip is quarantined
==> Propagating quarantine from /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip to /usr/local/Caskroom/gitkraken/4.0.6
/usr/bin/xattr -p com.apple.quarantine /Users/lantrix/Library/Caches/Homebrew/downloads/2bbc53d022fae9ee6bee036f96a625f07cda4758e06b0366b1c3cffca65562a5--GitKraken-v4.0.6.zip
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w -s com.apple.quarantine 0181\;5bc7129c\;Homebrew\\x20Cask\;65D04108-5C58-4A5D-9B6C-2D2BDFBD2191
==> Creating metadata directory /usr/local/Caskroom/gitkraken/.metadata/4.0.6/20181024011635.735.
==> Creating metadata subdirectory /usr/local/Caskroom/gitkraken/.metadata/4.0.6/20181024011635.735/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00000001061ea0f8>
==> Installing artifact of class Cask::Artifact::App
Warning: It seems there is already an App at '/Applications/GitKraken.app'; overwriting.
==> Removing App '/Applications/GitKraken.app'.
==> Moving App 'GitKraken.app' to '/Applications/GitKraken.app'.
🍺  gitkraken was successfully installed!
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.8.0-22-g59a72b0
==> macOS
10.13.1
==> SIP
Enabled
==> Java
1.8.0_66
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4038 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (207 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1181 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (155 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.59.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
buo/cask-upgrade
homebrew/boneyard
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
homebrew/versions
microsoft/mssql-preview
vitorgalvao/tiny-scripts
```

**Comment by alexreg** [comment] 2018-11-04 03:52
This happens for me too, on a number of casks.

**Comment by amyspark** [comment] 2018-11-17 18:51
In Sierra, I get this (more details on the analysis in #52758 ):
```
amalia@Sakura:~$ codesign -v --strict --deep --verbose=2 /Applications/GitKraken.app/
/Applications/GitKraken.app/: bundle format is ambiguous (could be app or framework)
In subcomponent: /Applications/GitKraken.app/Contents/Frameworks/ReactiveCocoa.framework
```

**Comment by amyspark** [comment] 2018-11-17 19:08
Update: manually unzipping the file as well as downloading it via Safari + unzipping it results in the same error. (It seems the developers didn't properly link the frameworks.)

**Comment by ran-dall** [comment] 2018-11-17 21:50
@amyspark I updated the cask today. I figured I'd give it a shot with the newest version, but it appears you're finding are correct. So I think it's working as intended.

Here's the output of the new version in the cask; and also a copy downloaded from their site.

```bash
🍺  gitkraken was successfully installed!
$ codesign -v --strict --deep --verbose=2 /Applications/GitKraken.app                                                                
/Applications/GitKraken.app: bundle format is ambiguous (could be app or framework)
In subcomponent: /Applications/GitKraken.app/Contents/Frameworks/Electron Framework.framework
 $codesign -v --strict --deep --verbose=2 /Users/draque/Downloads/GitKraken.app                                                  
/Users/draque/Downloads/GitKraken.app: bundle format is ambiguous (could be app or framework)
In subcomponent: /Users/randall/Downloads/GitKraken.app/Contents/Frameworks/Electron Framework.framework
```

**Comment by amyspark** [comment] 2018-11-18 01:57
Thanks for checking, @ran-dall! Closing as it's working as intended.

**Closed by amyspark** 2018-11-18 01:57 UTC
Labels: awaiting user reply
