### ISSUE TITLE
Replace casks for GUI apps in place

### ISSUE THREAD

**Issue by tangentsoft** [Homebrew/homebrew-cask#119449] opened 2022-02-20 08:20 UTC
### Provide a detailed description of the proposed feature

When upgrading casks, the replacement of the old version should be as much like dragging and dropping a `.app` file from a DMG as possible, to work with macOS's assorted UI mechanisms better.

Better, the replacement should be as smooth as installing updates from the App Store, such that I don't have to accept the new code-signing dialog manually, either. Once should suffice.

### What is the motivation for the feature?

Every upgrade to [Calibre](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/calibre.rb) currently drops it off my Dock. On replacing and running the new version, macOS insists I tell it my preferences for Notifications for this app, even though there's no reason to believe they have changed since the last version.

I believe this is because macOS can't see that I'm just installing a new version of the app via `brew upgrade`.

### Example use case

Nothing special. `brew upgrade` shouldn't drop casks off the Dock, old settings for Notifications for that app shouldn't be reset, and so forth.

**Comment by carlocab** [comment] 2022-02-20 08:24
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/102721

**Closed by carlocab** 2022-02-20 08:24 UTC
