### ISSUE TITLE
chromium.rb

### ISSUE THREAD

**Issue by Dmole** [Homebrew/homebrew-cask#141437] opened 2023-02-16 09:57 UTC
```
brew upgrade --greedy
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/chromium.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:46:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/upgrade.rb:98:in `upgrade_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by miccal** [comment] 2023-02-16 10:08
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/141436

**Closed by miccal** 2023-02-16 10:08 UTC
