### ISSUE TITLE
Uninstall google-backup-and-sync

### ISSUE THREAD

**Issue by fmozturk** [Homebrew/homebrew-cask#52544] opened 2018-09-27 11:11 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

While trying to uninstall google-backup-and-sync, I got error.

#### Command that failed

```
brew cask uninstall --verbose --debug --force google-backup-and-sync
```

#### Output of command with `--force --verbose --debug`

```
==> Uninstalling Cask google-backup-and-sync
==> Uninstalling Cask google-backup-and-sync
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x00007fc30538c730>
==> Un-installing artifact of class Cask::Artifact::Uninstall
==> Running uninstall process for google-backup-and-sync; your password may be necessary
==> Quitting application ID com.google.GoogleDrive
/bin/launchctl list
==> Removing login item Backup and sync from Google
/usr/bin/osascript -e tell\ application\ \"System\ Events\"\ to\ delete\ every\ login\ item\ whose\ name\ is\ \"Backup\ and\ sync\ from\ Google\"
36:103: execution error: -610 türünde bir hata oluştu. (-610)
Error: Failure while executing; `/usr/bin/osascript -e tell\ application\ \"System\ Events\"\ to\ delete\ every\ login\ item\ whose\ name\ is\ \"Backup\ and\ sync\ from\ Google\"` exited with 1. Here's the output:
36:103: execution error: -610 türünde bir hata oluştu. (-610)


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:105:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:48:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:25:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:171:in `block in uninstall_login_item'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:169:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:169:in `uninstall_login_item'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:59:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:55:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:55:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:493:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:489:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:442:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'

```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.6-22-gdae4791
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_181
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4036 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (201 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1177 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.0.5/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
ethereum/ethereum
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/science
homebrew/services
```

**Comment by vitorgalvao** [comment] 2018-10-03 17:48
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/50413

**Closed by vitorgalvao** 2018-10-03 17:48 UTC
