### ISSUE TITLE
Unable to update Google Chrome using Homebrew cask while initializing SSD with macOS Disk Utility.app

### ISSUE THREAD

**Issue by RintaroYamada** [Homebrew/homebrew-cask#143877] opened 2023-03-28 01:41 UTC
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

**Environment where the problem occurred:**

OS: macOS Ventura 13.2.1
Device: 13-inch, 2020, Four Thunderbolt 3 ports
CPU: 2.0GHz quad-core 10th-generation Intel Core i5, Turbo Boost up to 3.8GHz, with 6MB shared L3 cache
Language environment: Japanese
SSD to be initialized: Micron Crucial X6 SSD Media

**Contents:**
While initializing an SSD with macOS Disk Utility.app, I tried to update Google Chrome using Homebrew cask in iTerm2.app (version 3.4.19). However, even after waiting for a while, Google Chrome could not be installed. After killing the task and retrying several times, I noticed that a disk image named "Google Chrome" had been created in the SSD that I wanted to initialize. The disk image was created for each time I had tried to install Google Chrome. I had to force-quit Disk Utility.app, reboot, and reinstall Google Chrome again with the Homebrew command to finally get it installed.

In the attached images, you can see the terminal commands that were typed when Google Chrome could not be installed, a screenshot of the terminal after rebooting with Google Chrome installed, and a screenshot of Disk Utility.app showing the "Google Chrome" disk image.

I hope this issue can be investigated and resolved to prevent similar occurrences in the future. Thank you for your attention to this matter.

**
![2023-03-28 9 17のイメージ](https://user-images.githubusercontent.com/90881126/228103404-eb4c53ca-7318-47bd-bcac-f560a7c395c3.jpeg)
![2023-03-28 8 48のイメージ](https://user-images.githubusercontent.com/90881126/228103416-889e66b0-2573-4668-b076-256a681ddd59.jpeg)
![2023-03-28 8 55のイメージ](https://user-images.githubusercontent.com/90881126/228103420-0fa3d0a0-f184-41f8-8656-e06c46645751.jpeg)
![2023-03-28 9 42のイメージ](https://user-images.githubusercontent.com/90881126/228103424-d9bb0e8f-ce85-43e7-a30b-21d827a2d2c1.jpeg)
**

### Command that failed

brew upgrade --cask --greedy

### Output of command with `--verbose --debug`

```shell
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --user-agent Homebrew/4.0.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 13.2.1\)\ curl/7.86.0 --header Accept-Language:\ en --fail --location --remote-time --output /Users/rintaro_yamada/Library/Caches/Homebrew/api/cask.jws.json --time-cond /Users/rintaro_yamada/Library/Caches/Homebrew/api/cask.jws.json --compressed --speed-limit 100 --speed-time 5 https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  920k  100  920k    0     0  1581k      0 --:--:-- --:--:-- --:--:-- 1602k
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading adobe-acrobat-pro
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading anki
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading appcleaner
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading audio-hijack
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading clip-studio-paint
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading clipy
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading discord
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading github
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading google-chrome
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading hex-fiend
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading imageoptim
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading iterm2
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading karabiner-elements
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading mi
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading microsoft-edge
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading microsoft-excel
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading microsoft-powerpoint
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading microsoft-word
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading notion
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading pycharm
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading steam
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading visual-studio-code
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading vmware-fusion
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading webex
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading xquartz
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading zoom
```

### Output of `brew doctor` and `brew config`

```shell
~
❯ brew doctor
Your system is ready to brew.

~ 8s
❯ brew config
HOMEBREW_VERSION: 4.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: cf6614b50eac1c9f4bf386dc6989f0d443148df8
Last commit: 12 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1679db963e5c9a033ea4cbb4dab3d56f13021d31
Core tap last commit: 6 weeks ago
Core tap branch: master
Core tap JSON: 28 Mar 00:39 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.KpWDyKjYzo/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### Output of `brew tap`

```shell
~
❯ brew tap
candid82/brew
homebrew/bundle
homebrew/cask
homebrew/core
```

**Comment by RintaroYamada** [comment] 2023-03-31 01:50
@razvanazamfirei 

Thank you for your reply.
This non-critical bug occurred in a somewhat specific environment, but we had to initialize the SSD twice.
I believe this problem needs to be resolved, but I have no idea how to fix it.

**Comment by razvanazamfirei** [comment] 2023-03-31 12:15
Hi @RintaroYamada, based on the information you provided, it appears that the issue is caused by attempting to perform a `brew upgrade` while concurrently performing another `diskutil' operation. `brew upgrade` will wait for the disk formatting to complete. While I can't replicate your exact environment, in my testing the cask completed installing once the first  `diskutil' operation was done.

To avoid this issue in the future, I would recommend waiting until disk formatting is complete before running `brew upgrade`, as the two will not run concurrently. This is unlikely to be a `brew` problem, rather it's an OS limitation. 

Thank you again for your effort to replicate and report the issue. If you see other unexpected homebrew behavior, please let us know. I'll be closing this for now.

**Closed by razvanazamfirei** 2023-03-31 12:15 UTC
