### ISSUE TITLE
HOMEBREW_CASK_OPTS appdir not being honoured in Cask DSL

### ISSUE THREAD

**Issue by thoran** [Homebrew/homebrew-cask#140643] opened 2023-02-06 07:25 UTC
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

If appdir is set: HOMEBREW_CASK_OPTS="--appdir=~/Applications", then all reference to appdir remains as `/Applications`.

### Command that failed

brew install macdown

### Output of command with `--verbose --debug`

```shell
$ brew install macdown
==> Downloading https://github.com/MacDownApp/macdown/releases/download/v0.7.2/MacDown.app.zip
Already downloaded: /Users/thoran/Library/Caches/Homebrew/downloads/6997abe110b2dc77023e7a133ea1024423e1dbfb09ad48b9396e9f9023bb4d4b--MacDown.app.zip
==> Installing Cask macdown
==> Moving App 'MacDown.app' to '/Users/thoran/Applications/MacDown.app'
==> Backing App 'MacDown.app' up to '/opt/homebrew/Caskroom/macdown/0.7.2/MacDown.app'
==> Removing App '/Users/thoran/Applications/MacDown.app'
==> Purging files for version 0.7.2 of Cask macdown
Error: It seems the symlink source '/Applications/MacDown.app/Contents/SharedSupport/bin/macdown' is not there.
```

### Output of `brew doctor` and `brew config`

```shell
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 3.6.20-261-gb3a71ba
ORIGIN: https://github.com/Homebrew/brew
HEAD: b3a71ba7cdb7e005c26c86bcc627f0549dfe19d0
Last commit: 14 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 15cc58f490ef218e460352ccd00ebf79f35b2491
Core tap last commit: 6 hours ago
Core tap branch: master
Core tap JSON: 06 Feb 06:22 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications", "--fontdir=/Library/Fonts"]
HOMEBREW_DISPLAY: localhost:0.0
HOMEBREW_EDITOR: /usr/bin/vi
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

### Output of `brew tap`

```shell
heroku/brew
homebrew/bundle
homebrew/cask
homebrew/core
homebrew/services
thoran/tap
```

**Comment by Rylan12** [comment] 2023-02-06 07:27
Duplicate of https://github.com/Homebrew/brew/issues/14505

**Comment by Rylan12** [comment] 2023-02-06 07:28
This does need to be handled better so that the messaging is clear on how to fix it, though. For now, the fix is to set `HOMEBREW_NO_INSTALL_FROM_API`. Closing since there's already an issue open for this in Homebrew/brew

**Closed by Rylan12** 2023-02-06 07:28 UTC
