### ISSUE TITLE
FileZilla Client cask fails

### ISSUE THREAD

**Issue by Lillecarl** [Homebrew/homebrew-cask#51568] opened 2018-09-03 08:45 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

When installing FileZilla client it fails with HTTP errorcode 416. Download link works fine in Chrome, does not work when calling curl, wget is downloading it just fine, sha256 matches downloaded file too.

#### Command that failed

```
brew cask install filezilla --force --verbose --debug
```

#### Output of command with `--force --verbose --debug`

```
Updating Homebrew...
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.36.0_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --silent --head --write-out \%\{redirect_url\} --output /dev/null https://download.filezilla-project.org/client/FileZilla_3.36.0_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/lillecarl/Library/Caches/Homebrew/Cask/filezilla--3.36.0.tar.bz2.incomplete https://download.filezilla-project.org/client/FileZilla_3.36.0_macosx-x86.app.tar.bz2
** Resuming transfer from byte position 10610296
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 416
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/lillecarl/Library/Caches/Homebrew/Cask/filezilla--3.36.0.tar.bz2.incomplete https://download.filezilla-project.org/client/FileZilla_3.36.0_macosx-x86.app.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.1M  100 10.1M    0     0   291k      0  0:00:35  0:00:35 --:--:--  335k
curl: (16) Error in the HTTP2 framing layer
Error: Download failed on Cask 'filezilla' with message: Download failed: https://download.filezilla-project.org/client/FileZilla_3.36.0_macosx-x86.app.tar.bz2
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:39:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:35:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/download.rb:15:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:140:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:57:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.7.2
Homebrew/homebrew-cask (git revision 73926; last commit 2018-09-02)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4045 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
crisidev/chunkwm
homebrew/cask
homebrew/core
homebrew/services
jeffreywildman/virt-manager
koekeishiya/formulae
```

**Comment by Lillecarl** [comment] 2018-09-03 08:47
Removed the filezilla file from /Users/lillecarl/Library/Caches/Homebrew/Cask/ and tried downloading again, didn't make a difference.

**Comment by micdah** [comment] 2018-09-10 14:55
This might not be related, but I have previously had issues with HTTP/2 when the backend didn't support it, specifically with a nginx ingress controller in that particular case.

We experienced different behaviour because only some tools utilise HTTP/2 whereas others do not - so it seemed random, but turned out to be not.

I'm not convinced this is the case here - but the error just triggered my memory regarding that error. 😄

**Comment by vitorgalvao** [comment] 2018-09-10 15:15
Closing for lack of reply.

**Comment by laris** [comment] 2018-09-18 10:01
looks like filezilla website have special restriction.

brew cask reinstall filezilla
==> Satisfying dependencies
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Error: Download failed on Cask 'filezilla' with message: Download failed: https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2


wget https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
--2018-09-18 17:52:14--  https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
Resolving download.filezilla-project.org (download.filezilla-project.org)... 136.243.154.86, 2a01:4f8:171:1ce9::2
Connecting to download.filezilla-project.org (download.filezilla-project.org)|136.243.154.86|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10621590 (10M) [application/x-bzip2]
Saving to: ‘FileZilla_3.37.0_macosx-x86.app.tar.bz2’

FileZilla_3.37.0_macosx-x86.app.tar.bz2                     100%[=========================================================================================================================================>]  10.13M   177KB/s    in 63s

2018-09-18 17:53:18 (166 KB/s) - ‘FileZilla_3.37.0_macosx-x86.app.tar.bz2’ saved [10621590/10621590]

**Comment by laris** [comment] 2018-09-18 10:06
`brew cask reinstall filezilla --force --verbose --debug
==> Cask::Installer#reinstall
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --head --range 0-1 --write-out \%\{http_code\} --output /dev/null https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/laris/Library/Caches/Homebrew/downloads/0c8955f33cd033e0f9d95957818649ce3abf2fcf5c4bfc8ffef2a4c54920a812--FileZilla_3.37.0_macosx-x86.app.tar.bz2.incomplete https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
** Resuming transfer from byte position 10621590
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 416
Error: Download failed on Cask 'filezilla' with message: Download failed: https://download.filezilla-project.org/client/FileZilla_3.37.0_macosx-x86.app.tar.bz2
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:292:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:287:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:18:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:146:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:124:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:11:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'`

**Comment by vitorgalvao** [comment] 2018-09-18 11:15
@laris If you want us to look at this, please open a new issue and be sure to follow the template, do the steps it asks, and [answer this question](https://github.com/Homebrew/homebrew-cask/issues/51568#issuecomment-418099991).

Also, please make sure to always put your code in code blocks. You’re second post is nearly unreadable.

I still cannot reproduce.

**Closed by vitorgalvao** 2018-09-18 11:15 UTC
Labels: awaiting user reply
