### ISSUE TITLE
Error when installing blender from cask

### ISSUE THREAD

**Issue by jaimejim** [Homebrew/homebrew-cask#141439] opened 2023-02-16 10:28 UTC
Here is the output, don't know if there is something on my side too:

```
❯ brew install --cask blender
Error: No file found at https://raw.githubusercontent.com/Homebrew/homebrew-cask/cc58401c0905753619a9fc12dc733518beb75b05/Casks/blender.rb
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/api.rb:105:in `fetch_file_source'
/usr/local/Homebrew/Library/Homebrew/api/cask.rb:20:in `fetch_source'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:236:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:376:in `load'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:129:in `load_formula_or_cask'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:57:in `block in to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:56:in `each'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:56:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/cli/named_args.rb:56:in `to_formulae_and_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:176:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'


```

**Comment by miccal** [comment] 2023-02-16 10:29
Duplicate of https://github.com/Homebrew/homebrew-cask/issues/141436

**Closed by miccal** 2023-02-16 10:29 UTC
