### ISSUE TITLE
Intel Power Gadget failed proper download

### ISSUE THREAD

**Issue by Jahhein** [Homebrew/homebrew-cask#50622] opened 2018-08-08 17:22 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [ ] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

[All the debug info gist](https://gist.github.com/Jahhein/6c4428e63e7d5a6ef43e680a3bb26650)

```shell
brew cask install --require-sha --verbose --force --debug intel-power-gadget
```

Downloaded file extension is missing (.dmg) and placing a correctly downloaded version into the cache doesn't force the install either.

`wget` is able to properly grab the diskimage from the command below.

`wget https://software.intel.com/file/655065/download\?\#.dmg`

I've tried playing with the cask but I'm not entirely sure what is causing the messed up file name.

#### Command that failed

```shell
brew cask install --require-sha --verbose --force --debug intel-power-gadget
```

#### Output of command with `--force --verbose --debug`

```shell
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
To install and/or use intel-power-gadget you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://software.intel.com/file/655065/download?#.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.1-175-g3bce1c7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --silent --head --write-out \%\{redirect_url\} --output /dev/null https://software.intel.com/file/655065/download\?\#.dmg
==> Downloading from https://software.intel.com/sites/default/files/managed/b1/ed/Intel%C2%AE%20Power%20Gadget%203.5.3.dmg
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.1-175-g3bce1c7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/jahhein/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065.incomplete https://software.intel.com/sites/default/files/managed/b1/ed/Intel\%C2\%AE\%20Power\%20Gadget\%203.5.3.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5120k  100 5120k    0     0  3564k      0  0:00:01  0:00:01 --:--:-- 3565k
==> Downloaded to -> /Users/jahhein/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065
==> Verifying download
==> Determining which verifications to run for Cask intel-power-gadget
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask intel-power-gadget
==> SHA256 checksums match
==> Installing Cask intel-power-gadget
==> Hbc::Installer#stage
hdiutil imageinfo /Users/jahhein/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065
==> Extracting primary container
==> Using container class UnpackStrategy::Uncompressed for /Users/jahhein/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065
cp -p /Users/jahhein/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065 /usr/local/Caskroom/intel-power-gadget/3.5.3,655065/download
==> Creating metadata directory /usr/local/Caskroom/intel-power-gadget/.metadata/3.5.3,655065/20180808171446.822.
==> Creating metadata subdirectory /usr/local/Caskroom/intel-power-gadget/.metadata/3.5.3,655065/20180808171446.822/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007f8a8151eda8>
==> Installing artifact of class Hbc::Artifact::Pkg
==> Running installer for intel-power-gadget; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> Purging files for version 3.5.3,655065 of Cask intel-power-gadget
Error: pkg source file not found: 'Install Intel Power Gadget.pkg'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:40:in `run_installer'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/pkg.rb:31:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:192:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:184:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:91:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
```

#### Output of `brew cask doctor`

```shell
==> Homebrew-Cask Version
Homebrew-Cask 1.7.1-175-g3bce1c7
Homebrew/homebrew-cask (git revision 1752b0; last commit 2018-08-08)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
10.0.2, 1.8.0_172
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (1 files, 5MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4019 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (192 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1164 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (152 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

#### Output of `brew tap`

```shell
beeftornado/rmtree
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/livecheck
homebrew/services
vitorgalvao/tiny-scripts
```

**Comment by vitorgalvao** [comment] 2018-08-08 17:42
The issue has nothing to do with the download; that is fine.

> Error: pkg source file not found: 'Install Intel Power Gadget.pkg'

[That’s the issue](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#source-is-not-there-error). Here’s [how to fix it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_fix.md).

**Comment by Jahhein** [comment] 2018-08-08 17:48
Fixed my issue, the debug info wasn't correct.

**Comment by vitorgalvao** [comment] 2018-08-08 18:54
The problem (and solution) remain the same. Would you mind taking a crack at it?

**Comment by Jahhein** [comment] 2018-08-08 18:56
I'm trying to understand the stanzas. It just doesn't make sense how it not being a .dmg isn't the issue. the package is there in the download, just wrong extension. However I'm not familiar with the recent changes that have been going on with brew/cask

**Comment by vitorgalvao** [comment] 2018-08-08 19:01
> It just doesn't make sense how it not being a .dmg isn't the issue. 

Because an extension doesn’t determine a filetype, and we’re accurately detecting it’s a dmg and mounting it:

> ==> Hbc::Installer#stage
> hdiutil imageinfo /Users/jahhein/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065

> However I'm not familiar with the recent changes that have been going on with brew/cask

There are not recent changes that affect this. This problem and fix has been valid since the beginning.

Have you read the links I’ve posted? They explain the issue in detail.

**Comment by vitorgalvao** [comment] 2018-08-08 19:08
Actually, I tried it on a clean VM and I’m not being able to reproduce your issue at all.

**Closed** 2018-08-08 19:25 UTC

**Comment by cjs** [comment] 2018-08-21 16:30
FWIW I see this exact issue. `hdiutil` doesn't recognize the image unless there's a `.dmg` at the end:

```
cjs@eeyore:Cask $ hdiutil imageinfo intel-power-gadget--3.5.3,655065
hdiutil: imageinfo failed - image not recognized
cjs@eeyore:Cask $ mv intel-power-gadget--3.5.3,655065 intel-power-gadget--3.5.3,655065.dmg
cjs@eeyore:Cask $ hdiutil imageinfo intel-power-gadget--3.5.3,655065.dmg
Backing Store Information:
        URL: file:///Users/cjs/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065.dmg
        Name: intel-power-gadget--3.5.3,655065.dmg
        Class Name: CBSDBackingStore
...
```

**Comment by Jahhein** [comment] 2018-08-27 05:28
Thank you @cjs for letting me know that, glad I am not the only one. My brew install has been maintaining itself for the last 2 years. With the recent updates & prolonged outdated brew on my end, I figured my install was becoming unstable. 

@vitorgalvao any recommendations as a maintainer to uninstall homebrew & reinstall? Leaving cask installs alone, as they are the largest in memory, and then configure homebrew to see those casks again after reinstalling?

**Comment by vitorgalvao** [comment] 2018-08-27 13:12
@Jahhein Search the [FAQ](https://docs.brew.sh/FAQ) for “How do I uninstall Homebrew?”.

**Comment by Jahhein** [comment] 2018-08-27 14:36
@vitorgalvao I know of that, I was asking if there is a way to not completely uninstall the casks. If you reinstall won't homebrew not maintain cask apps installed?

**Comment by vitorgalvao** [comment] 2018-08-27 15:13
@Jahhein Casks can contain so many types of software, it’s hard to say. But the vast majority (`app`s, `font`s, and the like) shouldn’t be affected as we *move* those to their respective directories on the system.

You’ll lose the record of them being installed with HBC, though. Meaning `brew cask upgrade` and similar won’t include them until you overwrite them with cask versions (`brew cask reinstall --force`).

**Comment by revolter** [comment] 2018-08-27 19:14
@vitorgalvao, I followed the steps in the linked document and there is nothing wrong:

![image](https://user-images.githubusercontent.com/5748627/44680473-7c9e9380-aa46-11e8-8e65-00230e5e4eaa.png)

```ruby
cask 'intel-power-gadget' do
  version '3.5.3,655065'
  sha256 'a148715a956f1049a81a420244c919cf6f1678bbece9f79a42167c5485e83ded'

  url "https://software.intel.com/file/#{version.after_comma}/download?#.dmg"
  name 'Intel Power Gadget'
  homepage 'https://software.intel.com/en-us/articles/intel-power-gadget-20'

  pkg 'Install Intel Power Gadget.pkg'

  uninstall pkgutil: 'com.intel.pkg.PowerGadget.*',
            kext:    'EnergyDriver'
end
```

**Comment by vitorgalvao** [comment] 2018-08-27 19:18
@revolter https://github.com/Homebrew/homebrew-cask/issues/50622#issuecomment-411518381.

**Comment by vitorgalvao** [comment] 2018-08-27 20:31
@revolter Try [`container type:`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/all_stanzas.md) (scroll down), or [forcing the extension](https://github.com/Homebrew/homebrew-cask/blob/7c95720029c5b63927cc4a8c316ad625238f04fc/Casks/jaksta-media-recorder.rb#L14L15), or [maybe it’s a bad dmg](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/parallels-access.rb#L9L10). Use `stage_only` true to see how it unpacks to the Cache, and figure out the file structure as we get it.

**Comment by MTCoster** [comment] 2018-08-31 11:51
I just encountered this issue on a brand new mac - this was one of the first casks I tried to install

**Comment by vitorgalvao** [comment] 2018-08-31 12:12
@MTCoster https://github.com/Homebrew/homebrew-cask/issues/50622#issuecomment-416358612.

**Comment by MTCoster** [comment] 2018-08-31 14:27
Adding `container type: :dmg` to force the file type produces this new error (line breaks added for readability):

    Error: Failure while executing; `hdiutil convert -quiet -format UDTO -o
        /var/folders/cr/twg5d9155w32ktx33lgr0mhr0000gn/T/d20180831-1177-1kir18g/intel-power-gadget--3.5.cdr
        /Users/Matt/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065` exited with 1.

Removing the `-quiet` flag and running `hdiutil` manually produces this error message:

    hdiutil: convert failed - image not recognized

Adding `.dmg` to the the original file and running again seems to succeed.  Forcing the extension seems unnecessarily hacky, so I did a little digging and found an argument to tell `hdiutil` about the input file: `-srcimagekey diskimage-class=CRawDiskImage`

Here's the final command and its output (without `-quiet`):

    $ hdiutil convert -srcimagekey diskimage-class=CRawDiskImage -quiet -format UDTO -o /var/folders/cr/twg5d9155w32ktx33lgr0mhr0000gn/T/d20180831-1177-1kir18g/intel-power-gadget--3.5.cdr /Users/Matt/Library/Caches/Homebrew/Cask/intel-power-gadget--3.5.3,655065
    
    Reading Protective Master Boot Record (MBR : 0)…
    Reading GPT Header (Primary GPT Header : 1)…
    Reading GPT Partition Data (Primary GPT Table : 2)…
    Reading  (Apple_Free : 3)…
    Reading Intel® Power Gadget (Apple_HFS : 4)…
    ..........................................................................................................................................
    Reading  (Apple_Free : 5)…
    Reading GPT Partition Data (Backup GPT Table : 6)…
    ..........................................................................................................................................
    Reading GPT Header (Backup GPT Header : 7)…
    ..........................................................................................................................................
    Elapsed Time:  11.224ms
    Speed: 445.5Mbytes/sec
    Savings: 0.0%
    created: /var/folders/cr/twg5d9155w32ktx33lgr0mhr0000gn/T/d20180831-1177-1kir18g/intel-power-gadget--3.5.cdr

I have no idea how to implement that option, but if someone can give me a pointer I'll submit a PR.

**Comment by vitorgalvao** [comment] 2018-08-31 14:32
@MTCoster Submit the PR with [this method](https://github.com/Homebrew/homebrew-cask/blob/7c95720029c5b63927cc4a8c316ad625238f04fc/Casks/jaksta-media-recorder.rb#L14L15).

> Forcing the extension seems unnecessarily hacky

It is hacky, but not unnecessarily so.

> I have no idea how to implement that option, but if someone can give me a pointer I'll submit a PR.

You can’t do it on the cask, only by fixing this in HB’s code, like the comment mentions.

So your PR options are either fixing the problem for all casks in the core, or the hack for the cask. Naturally the former will be more beneficial, but it’s also more work that I’m not sure if you want to take or not.

**Comment by MTCoster** [comment] 2018-08-31 14:33
@vitorgalvao I'll take a look over the weekend at HB-core. If I can fix it there I will, otherwise I'll just do the quick fix over here.

**Comment by vitorgalvao** [comment] 2018-08-31 14:45
@MTCoster Sounds like a plan!

**Comment by MTCoster** [comment] 2018-08-31 15:18
Never mind, that was actually a pretty straightforward fix! https://github.com/Homebrew/brew/pull/4781
