### ISSUE TITLE
Logisim installation fails due to quarantine issue

### ISSUE THREAD

**Issue by nbrown** [Homebrew/homebrew-cask#51597] opened 2018-09-04 03:10 UTC
#### General troubleshooting steps

- [X] I have retried my command with `--force` and the issue is still present.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Installing logisim fails due to an inability to apply quarantine attribute.

#### Command that failed

```
brew cask install logisim
```

#### Output of command with `--force --verbose --debug`

```
○ → brew cask install --force --debug --verbose logisim
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://downloads.sourceforge.net/circuit/2.7.x/2.7.1/logisim-macosx-2.7.1.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz
==> /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz is quarantined
==> Downloaded to -> /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz
==> Verifying download
==> Determining which verifications to run for Cask logisim
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying SHA-256 checksum for Cask 'logisim'.
==> SHA-256 checksums match.
==> Installing Cask logisim
==> Hbc::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Tar for /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz
tar xf /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz -C /var/folders/9f/ylrpq8b91mz20rd86lzkyfkh0000gp/T/d20180903-5021-qrbvn0
cp -pR /var/folders/9f/ylrpq8b91mz20rd86lzkyfkh0000gp/T/d20180903-5021-qrbvn0/Logisim.app/. /usr/local/Caskroom/logisim/2.7.1/Logisim.app
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz
/usr/bin/xattr -p com.apple.quarantine /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz
==> /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz is quarantined
==> Propagating quarantine from /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz to /usr/local/Caskroom/logisim/2.7.1
/usr/bin/xattr -p com.apple.quarantine /Users/user/Library/Caches/Homebrew/downloads/c46dbdba80fcccb7187681d06a032be0eff1ab7d7f7a64b03e51d7af64026478--logisim-macosx-2.7.1.tar.gz
/usr/bin/xattr -w -rs com.apple.quarantine 0081\;5b8de653\;Homebrew-Cask\;685F945E-D194-432D-97CC-F5B6B34A7479 /usr/local/Caskroom/logisim/2.7.1
==> Purging files for version 2.7.1 of Cask logisim
Error: Failed to quarantine one or more files within /usr/local/Caskroom/logisim/2.7.1. Here's the reason:
xattr: [Errno 13] Permission denied: '/usr/local/Caskroom/logisim/2.7.1/Logisim.app/Contents/MacOS/JavaApplicationStub'

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/quarantine.rb:77:in `propagate'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:189:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:73:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:95:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:90:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:161:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:144:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:121:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

```

#### Output of `brew cask doctor`

```
○ → brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libr2.0.10.4-git.dylib

```

#### Output of `brew tap`

```
○ → brew tap
homebrew/binary
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/completions
homebrew/core
homebrew/dupes
homebrew/gui
homebrew/science
homebrew/services
homebrew/versions
universal-ctags/universal-ctags
```

**Comment by vitorgalvao** [comment] 2018-09-04 17:34
Not `brew doctor`, `brew cask doctor`.

Also, duplicate of https://github.com/Homebrew/homebrew-cask/issues/51538.

**Closed by vitorgalvao** 2018-09-04 17:34 UTC
