### ISSUE TITLE
Error: undefined method `undent' when updating rstudio

### ISSUE THREAD

**Issue by neiljdo** [Homebrew/homebrew-cask#49728] opened 2018-07-17 07:43 UTC
When trying to upgrade rstudio (via the line below), I receive the error above eventually

```
$ brew cask upgrade rstudio
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.7.leopard_64.bottle.tar.gz
==> Auto-updated Homebrew!
Updated 4 taps (homebrew/cask, homebrew/cask-versions, homebrew/core, microsoft/mssql-release).
==> New Formulae
amtk                                                microsoft/mssql-release/mssql-tools@17.2.0.1        pyside                                              xcodegen
microsoft/mssql-release/msodbcsql17@17.2.0.1        mkcert                                              python-yq
==> Updated Formulae
erlang ✔                                  coq                                       gr-osmosdr                                mvtools                                   selenium-server-standalone
harfbuzz ✔                                credstash                                 gradle                                    mypy                                      sfk
imagemagick ✔                             creduce                                   gron                                      nats-streaming-server                     shairport-sync
libgpg-error ✔                            csvkit                                    groovy                                    neomutt                                   shfmt
lua ✔                                     curl                                      groovysdk                                 nginx                                     singular
...

==> Upgrading 1 outdated package, with result:
rstudio 1.1.453
Error: undefined method `undent' for #<String:0x000000010110d4a0>
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Caskroom/rstudio/.metadata/1.0.153/20171018001652.007/Casks/rstudio.rb:21:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:36:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:36:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:67:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:15:in `cask'
/usr/local/Caskroom/rstudio/.metadata/1.0.153/20171018001652.007/Casks/rstudio.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:170:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:37:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/upgrade.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by bytecodeguru** [comment] 2018-07-17 08:38
Same for me when running `cask outdated`
```
Error: undefined method `undent' for #<String:0x0000000101642ad8>
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Caskroom/jce-unlimited-strength-policy/.metadata/1.8/20161019234048.037/Casks/jce-unlimited-strength-policy.rb:35:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:36:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:36:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:67:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:15:in `cask'
/usr/local/Caskroom/jce-unlimited-strength-policy/.metadata/1.8/20161019234048.037/Casks/jce-unlimited-strength-policy.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:34:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:28:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/caskroom.rb:28:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/outdated.rb:13:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:47:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/outdated.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
```

**Comment by vitorgalvao** [comment] 2018-07-17 09:49
Next time, please fill the full template. Closing as a duplicate of https://github.com/Homebrew/homebrew-cask/issues/49716.

**Closed by vitorgalvao** 2018-07-17 09:49 UTC
