### ISSUE TITLE
Casks aren't searchable on fresh install of Homebrew, docs unclear about this

### ISSUE THREAD

**Issue by barszcz** [Homebrew/homebrew-cask#118150] opened 2022-01-25 19:51 UTC
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

On a fresh install of Homebrew (macOS 12.1), any invocation of `brew info` on a known Cask formula fails with `Error: Cask '[caskname]' is unavailable: No Cask with this name exists.` Likewise any `brew search` for a Cask formula won't show that Cask either. I get an error regardless of whether the `--cask` flag is passed; if I omit the flag the error becomes `Error: No available formula with the name "[caskname]".`

This appears to be because `homebrew/cask` isn't `brew tap`ped until the user attempts to `brew install` a Cask formula (how `brew install` knows to do this without having Casks tapped in the first place to know that a formula is a Cask, I don't know). Obviously a user will never notice this if they try to install a Cask before looking one up, but it's not mentioned in the instructions that a `brew tap homebrew/cask` is necessary before a user can begin to look up Casks from the shell.

It's kind of a weird gotcha and I thought something was broken with my install until I went ahead and tried `brew install spotify` anyway and everything suddenly worked. I think having a mention of this in `USAGE.md` or `error_examples.md` would be helpful. The other alternative would be to modify the brew installation script to tap homebrew/cask during it, but I imagine there might be reasons HB doesn't do that.

If I should resubmit this as a feature request rather than a bug report, let me know. I'm also happy to open a PR myself to fix this in the docs.

### Command that failed

brew info --cask spotify

### Output of command with `--verbose --debug`

```shell
Error: Cask 'spotify' is unavailable: No Cask with this name exists.

or

Error: No available formula with the name "spotify". Did you mean spotifyd, shpotify or gotify?

[Note I did not get a chance to run this with --verbose or --debug before I fixed the problem].
```

### Output of `brew doctor --verbose`

```shell
Your system is ready to brew.

[Likewise I did not get to run this one before fixing the issue]
```

### Output of `brew tap`

```shell
n/a
```

**Comment by Bo98** [comment] 2022-01-26 00:44
This is caused by GitHub code search being broken. I'll close this as a duplicate of https://github.com/Homebrew/brew/issues/12557, but I'll try look into implementing a fix at the weekend.

**Closed by Bo98** 2022-01-26 00:44 UTC

**Comment by barszcz** [comment] 2022-01-26 00:53
@Bo98 Thanks for the clarification and sorry for the dupe issue!
