### ISSUE TITLE
quarantine.swift:29:30: error: 'quarantinePropertiesKey' is only available on OS X 10.10 or newer

### ISSUE THREAD

**Issue by cbismuth** [Homebrew/homebrew-cask#51612] opened 2018-09-04 16:47 UTC
Hi,

Here is below an error while trying to install Qt Creator.

Feel free to ask me to do some more testing.

Thanks,
Chris

```
Christophes-MacBook:~ cbismuth$ brew cask install qt-creator
==> Satisfying dependencies
==> Downloading http://download.qt.io/official_releases/qtcreator/4.7/4.7.0/qt-creator-opensource-mac-x86_64-4.7.0.dmg
Already downloaded: /Users/cbismuth/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/quarantine.swift:29:30: error: 'quarantinePropertiesKey' is only available on OS X 10.10 or newer
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/quarantine.swift:29:30: note: add 'if #available' version check
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
Error: Failed to quarantine /Users/cbismuth/Library/Caches/Homebrew/downloads/d68e5b47cfd65e43d9d3b849b1aaec14c0b90e7b76e4ff97a7fa213409a1cca1--qt-creator-opensource-mac-x86_64-4.7.0.dmg. Here's the reason:
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/quarantine.swift:29:30: error: 'quarantinePropertiesKey' is only available on OS X 10.10 or newer
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/quarantine.swift:29:30: note: add 'if #available' version check
      forKey: URLResourceKey.quarantinePropertiesKey
                             ^

Christophes-MacBook:~ cbismuth$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G22010)
      Kernel Version: Darwin 15.6.0
      Boot Volume: OSX
      Boot Mode: Normal
      Computer Name: Christophe’s MacBook
      User Name: Christophe Bismuth (cbismuth)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:13
```

**Comment by cbismuth** [comment] 2018-09-04 16:48
```
Christophes-MacBook:~ cbismuth$ brew --version
Homebrew 1.7.3
Homebrew/homebrew-core (git revision 5e2ea; last commit 2018-09-04)
```

**Comment by vitorgalvao** [comment] 2018-09-04 17:33
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

Also note from that document:

> If the maintainer was wrong in closing your issue, please do reply stating why! Closing an issue does not mean the conversation is over. If the guides themselves were unclear, help us improve them! Open *first* an issue or pull request stating what you found confusing *and only then* your other issue.

**Comment by vitorgalvao** [comment] 2018-09-04 17:33
Also, duplicate of https://github.com/Homebrew/homebrew-cask/issues/51554.

**Closed by vitorgalvao** 2018-09-04 17:33 UTC
