### ISSUE TITLE
MacOS Catalina Dropbox fails to install

### ISSUE THREAD

**Issue by Donquicote** [Homebrew/homebrew-cask#70720] opened 2019-10-13 15:07 UTC
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Dropbox fails to install in MacOS Catalina

#### Command that failed

```
brew cask install dropbox
```

#### Output of command with `--force --verbose --debug`

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://www.dropbox.com/download?plat=mac&full=1
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.1.13-52-g16d477c\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15\)\ curl/7.64.1 --location --silent --head --request GET https://www.dropbox.com/download\?plat=mac\&full=1
Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.156.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.156.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox\ 82.4.156.dmg
==> /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.156.dmg is quarantined
==> Downloaded to -> /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.156.dmg
==> No SHA-256 checksum defined for Cask 'dropbox', skipping verification.
==> Installing Cask dropbox
==> Cask::Installer#stage
hdiutil imageinfo /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox\ 82.4.156.dmg
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.156.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/d20191013-37797-nllp54 /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox\ 82.4.156.dmg
find . -print0
mkbom -s -i /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/20191013-37797-lj2j2f.list -- /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/20191013-37797-6yl5l3.bom
ditto --bom /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/20191013-37797-6yl5l3.bom -- /private/var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/d20191013-37797-nllp54/dmg.wjyWcC /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/d20191013-37797-1fhnfa0
diskutil eject /private/var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/d20191013-37797-nllp54/dmg.wjyWcC
cp -pR /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/d20191013-37797-1fhnfa0/.dbx_preinstall /usr/local/Caskroom/dropbox/latest/.dbx_preinstall
cp -pR /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/d20191013-37797-1fhnfa0/Dropbox.app/. /usr/local/Caskroom/dropbox/latest/Dropbox.app
cp -pR /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/d20191013-37797-1fhnfa0/.dbx_install /usr/local/Caskroom/dropbox/latest/.dbx_install
chmod -Rf +w /var/folders/n2/c_8dkwsn6j3b_wm079r73tn00000gn/T/d20191013-37797-1fhnfa0
==> Verifying Gatekeeper status of /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.156.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox\ 82.4.156.dmg
==> /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.156.dmg is quarantined
==> Propagating quarantine from /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox 82.4.156.dmg to /usr/local/Caskroom/dropbox/latest
/usr/bin/xattr -p com.apple.quarantine /Users/xxx/Library/Caches/Homebrew/downloads/2c8afbdc56eb2cb1170f526424b46e25565b9acf4fecaa19b4b294cf1b3e9a7d--Dropbox\ 82.4.156.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5da31733\;Homebrew\\x20Cask\;651BB779-0C65-44AE-9B92-ABA52ECCA8C3
==> Purging files for version latest of Cask dropbox
Error: Failed to quarantine one or more files within /usr/local/Caskroom/dropbox/latest. Here's the reason:
xattr: No such file: /usr/local/Caskroom/dropbox/latest/Dropbox.app/Contents/Frameworks/Tungsten.framework/Versions/A/Frameworks/Chromium Embedded Framework.framework/Libraries

/usr/local/Homebrew/Library/Homebrew/cask/quarantine.rb:165:in `propagate'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:195:in `extract_primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:77:in `stage'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:99:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:23:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:162:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:146:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.1.13-52-g16d477c
==> macOS
10.15
==> SIP
Disabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3471 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.36.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.75.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.6.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.29.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.18.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/nokogiri-1.10.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/jaro_winkler-1.5.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-0.20.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.21.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-13/2.6.0-static/json-2.2.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-5.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.12.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.5/lib
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/core
```

**Comment by amyspark** [comment] 2019-10-14 20:36
Duplicate of #70796.

**Closed by amyspark** 2019-10-14 20:36 UTC
