### ISSUE TITLE
'brew cask info heaven' reports 'invalid 'depends_on macos' value: "mountain_lion".'

### ISSUE THREAD

**Issue by rhencke** [Homebrew/homebrew-cask#57994] opened 2019-01-27 18:27 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Running the command `brew cask info heaven` produces an error message stating `invalid 'depends_on macos' value: "mountain_lion"`.

#### Command that failed

```
brew cask info heaven
```

#### Output of command with `--force --verbose --debug`

n.b. The info command refuses to take the `--force` switch, so the below output is from `brew cask info heaven --verbose --debug`

```
Error: Cask 'heaven' definition is invalid: invalid 'depends_on macos' value: "mountain_lion"
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:214:in `rescue in depends_on'
/usr/local/Homebrew/Library/Homebrew/cask/dsl.rb:211:in `depends_on'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/heaven.rb:9:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:42:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:42:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:33:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:77:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:123:in `cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/heaven.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:60:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:180:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:50:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:50:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:50:in `casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/info.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.9.3-39-gd0202f6
==> macOS
10.14.2
==> SIP
Enabled
==> Java
1.8.0_181
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4102 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.63.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.6.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.13.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.5.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.4/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin18
/Library/Ruby/Site/2.3.0/universal-darwin18
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
atlassian/tap
hhvm/hhvm
homebrew/cask
homebrew/core
homebrew/services
```

**Comment by haykam821** [comment] 2019-01-27 18:53
[Valley cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/valley.rb#L9)

**Comment by jasmas** [comment] 2019-01-27 18:57
@haykam821 Tested and no luck. Depending on Mavericks or higher does fix and mountain_lion is no longer in the depends_on documentation. Was it removed? Note that fixing valley.rb to depend on mavericks or higher results in the same search failure due to heaven.rb... it seems both formula reference mountain_lion

**Comment by haykam821** [comment] 2019-01-27 19:08
@jasmas I did some digging and found [that pre-Mavericks dependencies were removed](https://github.com/Homebrew/homebrew-cask/pull/57235)... except not this one, apparently, since it was `mountain_lion` instead of `:mountain_lion`, so it was skipped over when searching. I'll just update it to `:mavericks` in my pull request since that's what they did in theirs.

**Comment by jasmas** [comment] 2019-01-27 19:08
Confirmed these are the only two formula on my machine still referencing 'mountain_lion'

`grep -RH mountain_lion .
./Taps/homebrew/homebrew-cask/Casks/valley.rb:  depends_on macos: '>= mountain_lion'
./Taps/homebrew/homebrew-cask/Casks/heaven.rb:  depends_on macos: '>= mountain_lion'
./Homebrew/test/version_spec.rb:        .to be_detected_from("https://homebrew.bintray.com/bottles/erlang-R15B01.mountain_lion.bottle.tar.gz")
./Homebrew/test/software_spec_spec.rb:      mountain_lion:   "8badf00d" * 8,`


`brew tap
buo/cask-upgrade
cloudflare/cloudflare
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
khell/srm
vitorgalvao/tiny-scripts`

**Comment by haykam821** [comment] 2019-01-27 19:12
@jasmas heaven.rb is now fixed in 1db31f077dac5a984a398025c8dc5c4735e67122.

**Closed** 2019-01-27 20:32 UTC

**Comment by ralphrmartin** [comment] 2019-02-24 08:12
This problem occurs for several other casks too: handbrake, spotify, the-unarchiver, for example. Something has changed in the infrastructure which is causing these casks to fail.

**Comment by ralphrmartin** [comment] 2019-02-24 08:14
Actually, these fail complaining about :lion, not :mountain-lion...

**Comment by ztarbugz** [comment] 2019-02-24 09:12
Running into same issue when cask tries to upgrade handbrake. Failing with depends_on lion message.

**Comment by mxr576** [comment] 2019-02-24 11:18
I have the same issue with Enpass...

```sh
Error: Cask 'enpass' definition is invalid: invalid 'depends_on macos' value: ":mountain_lion"
```

**Comment by vitorgalvao** [comment] 2019-02-24 15:21
https://github.com/Homebrew/homebrew-cask/issues/58046
