### ISSUE TITLE
dotnet/dotnet-sdk: does not add binary to PATH and has no Caveats

### ISSUE THREAD

**Issue by ahmetb** [Homebrew/homebrew-cask#52560] opened 2018-09-27 19:30 UTC
#### General troubleshooting steps

N/A since it's not a functional issue.

#### Description of issue

Right now casks `dotnet` and `dotnet-sdk` install the actual binary to `/usr/local/share/dotnet/dotnet`.

- They don't print any CAVEATS message urging the user to add this directory to their PATH.
- User cannot tell what exactly has happened after installing these two casks as no GUI program is installed and no cmd is added to user's current PATH.
- The `homepage` listed in cask (https://www.microsoft.com/net/core#macos) doesn't explain it either.

cc: @dasMulli

**Comment by vitorgalvao** [comment] 2018-09-27 20:49
Would you mind adding [the `caveat`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats-mini-dsl)? It’s the first one on the table: `path_environment_variable 'path'`.

[Example in `anaconda`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/anaconda.rb#L32L35).

**Comment by dasMulli** [comment] 2018-09-27 20:57
The pkg installer should add the path to `/etc/paths.d/dotnet` making it available to all new (!) shell instances.
unless you have an older oh-my-zsh installation which pinned the current PATH on first zsh install.

**Comment by ahmetb** [comment] 2018-09-27 21:08
As far as I can tell it didn't update my zshrc or bashrc.

Is the solution here to call `eval $(/usr/libexec/path_helper -s)` in the rc file? I recommend you to update the caveat, I'm not sure how to word this.

**Comment by reitermarkus** [comment] 2018-09-27 23:04
@ahmetb, what's the output of `cat /etc/paths.d/dotnet`?

**Comment by dasMulli** [comment] 2018-09-28 01:19
@ahmetb does the output of `/usr/libexec/path_helper` contain `/usr/local/share/dotnet`?
Does your zshrc set the PATH to a fixed value somewhere?

**Comment by ahmetb** [comment] 2018-09-30 23:50
> does the output of `/usr/libexec/path_helper` contain `/usr/local/share/dotnet`?

Yes. But this cmd somehow doesn't exist in original .zshrc that comes in oh-my-zsh. So people probably need to add it manually.

**Comment by reitermarkus** [comment] 2018-10-01 05:41
> Yes. But this cmd somehow doesn't exist in original .zshrc that comes in oh-my-zsh.

It doesn't need to be in `.zshrc`, it is built into the shell, unless you are using the brewed `zsh` with the `--without-etcdir` option. I cannot reproduce this by switching my shell to `zsh`, so it's an issue with your configuration. Try deleting your `.zshrc` to see if it works without any custom config.

**Comment by dasMulli** [comment] 2018-10-01 06:01
I believe the oh-my-zsh installer was eventually changed to not fix the $PATH on install. if you have an older install, your .zshrc may still re-set the PATH without taking into account the previous $PATH value.

**Comment by dasMulli** [comment] 2018-10-01 06:04
This has come up repeatedly on the dotnet/cli repo and was always considered to be an oh-my-zsh issue.
See
https://github.com/robbyrussell/oh-my-zsh/pull/4925
https://github.com/dotnet/cli/issues/1567

**Comment by vitorgalvao** [comment] 2018-10-01 07:31
Closing as an upstream issue. Thank you for the links and research, @dasMulli.

**Closed by vitorgalvao** 2018-10-01 07:31 UTC
