### ISSUE TITLE
Brew cask install fastlane fails with "uninitialized constant HashValidator::CaskError"

### ISSUE THREAD

**Issue by rahardin** [Homebrew/homebrew-cask#49513] opened 2018-07-11 15:33 UTC
---
name: Bug Report
about: Create a report to help us improve

---

#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Brew cask fails to install fastlane. 

#### Command that failed

```
brew cask install fastlane --force --verbose --debug
```

#### Output of command with `--force --verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://fastlane.tools/fastlane.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.6.13 (Macintosh; Intel Mac OS X 10.13.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/hardin/Library/Caches/Homebrew/Cask/fastlane--latest.zip.incomplete https://fastlane.tools/fastlane.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24.4M  100 24.4M    0     0  2810k      0  0:00:08  0:00:08 --:--:-- 2842k
==> Downloaded to -> /Users/hardin/Library/Caches/Homebrew/Cask/fastlane--latest.zip
==> Verifying download
==> Determining which verifications to run for Cask fastlane
==> Checking for verification class Hbc::Verify::Checksum
==> No checksum defined for Cask fastlane, skipping verification
==> 0 verifications defined
==> Installing Cask fastlane
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/hardin/Library/Caches/Homebrew/Cask/fastlane--latest.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/hardin/Library/Caches/Homebrew/Cask/fastlane--latest.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/hardin/Library/Caches/Homebrew/Cask/fastlane--latest.zip", "/var/folders/hl/h0mpsnhs47122rctprxbznm80000gn/T/d20180711-31406-u6locr"]
==> Creating metadata directory /usr/local/Caskroom/fastlane/.metadata/latest/20180711153109.396.
==> Creating metadata subdirectory /usr/local/Caskroom/fastlane/.metadata/latest/20180711153109.396/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x00007fa9d5ac33f8>
==> Installing artifact of class Hbc::Artifact::Installer
==> Running installer script 'install'
==> Purging files for version latest of Cask fastlane
Error: uninitialized constant HashValidator::CaskError
Did you mean?  ScanError
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/utils/hash_validator.rb:5:in `assert_valid_keys'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:48:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/installer.rb:26:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:176:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:168:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:82:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:33:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:93:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:157:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:145:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:122:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.6.13
Homebrew/homebrew-cask (git revision 153b2; last commit 2018-07-11)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
1.8.0_172
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 272.4MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3994 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (185 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/cask/lib
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

#### Output of `brew tap`

```
homebrew/cask
homebrew/cask-versions
homebrew/core
```

**Comment by vitorgalvao** [comment] 2018-07-11 15:38
@reitermarkus This is the second issue in an hour with `Error: uninitialized constant HashValidator::CaskError`, both on `1.6.13`. Must be something with that release.

**Comment by reitermarkus** [comment] 2018-07-11 16:05
Yes, this was caused by https://github.com/Homebrew/brew/pull/4265 and will be fixed with https://github.com/Homebrew/brew/pull/4453.

**Comment by reitermarkus** [comment] 2018-07-11 16:43
This is fixed now.

**Closed by reitermarkus** 2018-07-11 16:43 UTC
