### ISSUE TITLE
Unable to uninstall/install the-unarchiver cask

### ISSUE THREAD

**Issue by ricardojoaoreis** [Homebrew/homebrew-cask#145499] opened 2023-04-20 08:13 UTC
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Can't install `the-unarchiver` cask due to an error:
```
Error: Cask 'the-unarchiver' is unreadable: undefined method `before_colon' for "131:1605625663":Cask::DSL::Version
Did you mean?  before_comma
```

### Command that failed
```shell
brew uninstall the-unarchiver
```

### Output of command with `--verbose --debug`

```shell
brew uninstall --verbose --debug the-unarchiver
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading the-unarchiver
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /usr/local/Caskroom/the-unarchiver/.metadata/4.2.4,131:1605625663/20201216102418.004/Casks/the-unarchiver.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libtiff from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading yq from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading xorgproto from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libidn2 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libxau from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading little-cms2 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libpng from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading ncurses from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading pixman from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading mpdecimal from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libxdmcp from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading freetype from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading rtmpdump from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading pipx from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading liblinear from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libunistring from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading brotli from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading icu4c from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading harfbuzz from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading glib from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libxcb from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading readline from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openjdk@17 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading utf8proc from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading lz4 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading graphite2 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading cairo from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading sqlite from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading xz from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libnghttp2 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading bash from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading fontconfig from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gradle from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading htop from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openjdk from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading curl from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading giflib from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libxrender from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading ca-certificates from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading gettext from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libssh2 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading zstd from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading shellcheck from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading tmux from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libxext from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading watch from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading oniguruma from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading pcre2 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libevent from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openssl@1.1 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading pcre from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading lua@5.3 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading kubernetes-cli from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading ncdu from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading nmap from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading jq from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading openldap from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading python@3.11 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading fish from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading libx11 from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading fzf from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading git from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading lzo from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading jpeg-turbo from API
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading alacritty
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading bitwarden
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading charles
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading firefox
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading gpg-suite
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading insomnia
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading itsycal
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading jetbrains-toolbox
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading keepingyouawake
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading knockknock
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading notion
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading postman
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading rectangle
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading signal
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading sourcetree
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading spotify
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading telegram
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading the-unarchiver
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading ticktick
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading visual-studio-code
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading whatsapp
==> Uninstalling Cask the-unarchiver
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromPathLoader): loading /usr/local/Caskroom/the-unarchiver/.metadata/4.2.4,131:1605625663/20201216102418.004/Casks/the-unarchiver.rb
Error: Cask 'the-unarchiver' is unreadable: undefined method `before_colon' for "131:1605625663":Cask::DSL::Version
Did you mean?  before_comma
/usr/local/Caskroom/the-unarchiver/.metadata/4.2.4,131:1605625663/20201216102418.004/Casks/the-unarchiver.rb:5:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:93:in `refresh'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:86:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:76:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:59:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:59:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:107:in `cask'
/usr/local/Caskroom/the-unarchiver/.metadata/4.2.4,131:1605625663/20201216102418.004/Casks/the-unarchiver.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:92:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:92:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:387:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:555:in `load_installed_caskfile!'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:400:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/uninstall.rb:15:in `block in uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/uninstall.rb:10:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/uninstall.rb:10:in `uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:79:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Your system is ready to brew.

brew config
HOMEBREW_VERSION: 4.0.14-78-g36eadba
ORIGIN: https://github.com/Homebrew/brew
HEAD: 36eadba49af328f4f3414d55b55dba769a2ee35d
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 212adee0965772ff7aa36f907f97e6c4aa88e59c
Core tap last commit: 59 minutes ago
Core tap branch: master
Core tap JSON: 20 Apr 08:08 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications"]
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
```

### Output of `brew tap`

```shell
brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/core
```

**Comment by razvanazamfirei** [comment] 2023-04-20 10:23
Hi @ricardojoaoreis, this looks similar to https://github.com/Homebrew/homebrew-cask/issues/145073 and is caused by having an outdated version of the cask. We've moved from the colon syntax ~2 years ago. If you delete the URL stanza in 

`/usr/local/Caskroom/the-unarchiver/.metadata/4.2.4,131:1605625663/20201216102418.004/Casks/the-unarchiver.rb` 

you should be able to uninstall the cask. 

If that doesn't work, you could uninstall Unarchiver the regular macOS way and then run

`rm -r /usr/local/Caskroom/the-unarchiver`

to get rid of the Cask in Homebrew. 

I'm closing this for now, but let me know if this doesn't fix it.

**Closed by razvanazamfirei** 2023-04-20 10:23 UTC

**Comment by ricardojoaoreis** [comment] 2023-04-20 11:08
Yes, it solved the issue.

However I don't understand why `update-reset` and `update` didn't solve it… Will I need to do it again if I face this problem in the future with another cask?

**Comment by razvanazamfirei** [comment] 2023-04-20 12:27
Hi, @ricardojoaoreis. The commands `update-reset` and `update` will update `brew`, but not the casks. When you installed `the-unarchiver 4.2.4,131:1605625663` a few years ago, `brew` kept the cask file that was used at the time. However, we have since stopped using colons in our versioning. After a period of time, the parsing functionality for casks using colons was deprecated. This only becomes problematic when casks have not been updated locally for an extended period (e.g., years) because the syntax of the cask file does not get updated, and later versions of Homebrew cannot parse it.

Depending on which casks you have installed and the last time they were updated, this may surface again if you try to update a very old cask. I would encourage updating your casks by running `brew upgrade --greedy` as that should find casks with errors. 

Alternatively, you can run 
`brew list --casks --versions` and look for versions containing colons or `find "$(brew --caskroom)" -type d -name '*:*' 2>/dev/null` which will show the path to casks with versions containing colons.
