### ISSUE TITLE
Blender 2.8.2 - Catalina 10.15.3

### ISSUE THREAD

**Issue by Jarli01** [Homebrew/homebrew-cask#77813] opened 2020-02-27 13:51 UTC
#### General troubleshooting steps

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Blender 2.8.2 successfully installs, but Application size is 0 bytes, and when attempting to open the application results in "You do not have permission to open the application "Blender.app it may be damaged or incomplete".

Manually downloading the package from https://www.blender.org/download/ and installing the package file or using Apple's Remote Desktop package deployment tool works without issue. 

#### Command that failed

```
brew cask install blender
```

#### Output of command with `--force --verbose --debug`

```
brew cask install blender --force --verbose --debug
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
==> Downloading https://download.blender.org/release/Blender2.82/blender-2.82-ma
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.6-65-g955947c\                                                                                                                                                              \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.3\)\ curl/7.64.1 --location --silent --                                                                                                                                                             head --request GET https://download.blender.org/release/Blender2.82/blender-2.82                                                                                                                                                             -macOS.dmg
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa3                                                                                                                                                             76ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
==> /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg is quarantined
==> Downloaded to -> /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
==> Verifying SHA-256 checksum for Cask 'blender'.
hdiutil imageinfo -format /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
==> Installing Cask blender
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/d20200227-13676-1pp77ta /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
find . -print0
mkbom -s -i /var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/20200227-13676-13x29ug.list -- /var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/20200227-13676-ebqy5e.bom
ditto --bom /var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/20200227-13676-ebqy5e.bom -- /private/var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/d20200227-13676-1pp77ta/dmg.rVNMjH /var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/d20200227-13676-8lxon4
diskutil eject /private/var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/d20200227-13676-1pp77ta/dmg.rVNMjH
cp -pR /var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/d20200227-13676-8lxon4/Blender.app/. /usr/local/Caskroom/blender/2.82/Blender.app
chmod -Rf +w /var/folders/rb/hb1zwwns47x762c__25kl3g00000gn/T/d20200227-13676-8lxon4
==> Verifying Gatekeeper status of /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
==> /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg is quarantined
==> Propagating quarantine from /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg to /usr/local/Caskroom/blender/2.82
/usr/bin/xattr -p com.apple.quarantine /Users/admin/Library/Caches/Homebrew/downloads/b65e575140fa376ba319ad18bbb270e5bea1eae5975f569dd2a3f89a1aeeb476--blender-2.82-macOS.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;5e543e51\;Homebrew\\x20Cask\;73498634-E77E-4448-B3EB-8C388BC4D4EA
==> Creating metadata directory /usr/local/Caskroom/blender/.metadata/2.82/20200227134857.181.
==> Creating metadata subdirectory /usr/local/Caskroom/blender/.metadata/2.82/20200227134857.181/Casks.
==> Installing artifacts
==> 3 artifact/s defined
#<SortedSet: {#<Cask::Artifact::PreflightBlock:0x00007fd564a38a68 @cask=#<Cask::Cask:0x00007fd56495d990 @token="blender", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/blender.rb>, @tap=#<Tap:0x00007fd564121f60 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fd56495d7d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/blender.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/blender>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/blender/.metadata>, @config=#<Cask::Config:0x00007fd564a41c08 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/admin/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/admin/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/admin/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/admin/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/admin/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/admin/Library/Services>, :input_methoddir=>#<Pathname:/Users/admin/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/admin/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/admin/Library/Screen Savers>}, @env={}, @explicit={}, @binarydir=#<Pathname:/usr/local/bin>>, @dsl=#<Cask::DSL:0x00007fd564a41a78 @cask=#<Cask::Cask:0x00007fd56495d990 ...>, @token="blender", @version="2.82", @sha256="509b4235e589bc7a5794f484ba6c1ca9807c18d4e87e4f22576b4cc0be4bc383", @url=#<URL:0x00007fd564a411e0 @uri=#<URI::HTTPS https://download.blender.org/release/Blender2.82/blender-2.82-macOS.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fd564a40ce0 @uri=#<URI::HTTPS https://download.blender.org/release/>, @parameters={:configuration=>"2.82"}, @configuration="2.82">, @name=["Blender"], @homepage="https://www.blender.org/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/blender/2.82>, @language=nil>>, @directives={:preflight=>#<Proc:0x00007fd564a38ab8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/blender.rb:16>}>, #<Cask::Artifact::App:0x00007fd564a40628 @cask=#<Cask::Cask:0x00007fd56495d990 @token="blender", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/blender.rb>, @tap=#<Tap:0x00007fd564121f60 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fd56495d7d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/blender.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/blender>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/blender/.metadata>, @config=#<Cask::Config:0x00007fd564a41c08 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/admin/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/admin/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/admin/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/admin/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/admin/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/admin/Library/Services>, :input_methoddir=>#<Pathname:/Users/admin/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/admin/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/admin/Library/Screen Savers>}, @env={}, @explicit={}, @binarydir=#<Pathname:/usr/local/bin>>, @dsl=#<Cask::DSL:0x00007fd564a41a78 @cask=#<Cask::Cask:0x00007fd56495d990 ...>, @token="blender", @version="2.82", @sha256="509b4235e589bc7a5794f484ba6c1ca9807c18d4e87e4f22576b4cc0be4bc383", @url=#<URL:0x00007fd564a411e0 @uri=#<URI::HTTPS https://download.blender.org/release/Blender2.82/blender-2.82-macOS.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fd564a40ce0 @uri=#<URI::HTTPS https://download.blender.org/release/>, @parameters={:configuration=>"2.82"}, @configuration="2.82">, @name=["Blender"], @homepage="https://www.blender.org/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/blender/2.82>, @language=nil>>, @source_string="Blender.app", @target_string="", @source=#<Pathname:/usr/local/Caskroom/blender/2.82/Blender.app>, @target=#<Pathname:/Applications/Blender.app>>, #<Cask::Artifact::Binary:0x00007fd564a39b48 @cask=#<Cask::Cask:0x00007fd56495d990 @token="blender", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/blender.rb>, @tap=#<Tap:0x00007fd564121f60 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fd56495d7d8@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/blender.rb:1>, @caskroom_path=#<Pathname:/usr/local/Caskroom/blender>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/blender/.metadata>, @config=#<Cask::Config:0x00007fd564a41c08 @default={:appdir=>#<Pathname:/Applications>, :prefpanedir=>#<Pathname:/Users/admin/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/admin/Library/QuickLook>, :dictionarydir=>#<Pathname:/Users/admin/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/admin/Library/Fonts>, :colorpickerdir=>#<Pathname:/Users/admin/Library/ColorPickers>, :servicedir=>#<Pathname:/Users/admin/Library/Services>, :input_methoddir=>#<Pathname:/Users/admin/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/admin/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/admin/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/admin/Library/Screen Savers>}, @env={}, @explicit={}, @binarydir=#<Pathname:/usr/local/bin>>, @dsl=#<Cask::DSL:0x00007fd564a41a78 @cask=#<Cask::Cask:0x00007fd56495d990 ...>, @token="blender", @version="2.82", @sha256="509b4235e589bc7a5794f484ba6c1ca9807c18d4e87e4f22576b4cc0be4bc383", @url=#<URL:0x00007fd564a411e0 @uri=#<URI::HTTPS https://download.blender.org/release/Blender2.82/blender-2.82-macOS.dmg>, @user_agent=:default, @specs={}>, @appcast=#<Cask::DSL::Appcast:0x00007fd564a40ce0 @uri=#<URI::HTTPS https://download.blender.org/release/>, @parameters={:configuration=>"2.82"}, @configuration="2.82">, @name=["Blender"], @homepage="https://www.blender.org/", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/blender/2.82>, @language=nil>>, @source_string="/usr/local/Caskroom/blender/2.82/blender.wrapper.sh", @target_string="blender", @source=#<Pathname:/usr/local/Caskroom/blender/2.82/blender.wrapper.sh>, @target=#<Pathname:/usr/local/bin/blender>>}>
==> Installing artifact of class Cask::Artifact::PreflightBlock
==> Installing artifact of class Cask::Artifact::App
Warning: It seems there is already an App at '/Applications/Blender.app'; overwriting.
==> Removing App '/Applications/Blender.app'.
==> Moving App 'Blender.app' to '/Applications/Blender.app'.
==> Installing artifact of class Cask::Artifact::Binary
==> Linking Binary 'blender.wrapper.sh' to '/usr/local/bin/blender'.
/bin/ln -h -f -s -- /usr/local/Caskroom/blender/2.82/blender.wrapper.sh /usr/local/bin/blender
==> Adding com.apple.metadata:kMDItemAlternateNames metadata
/usr/bin/xattr -p com.apple.metadata:kMDItemAlternateNames /usr/local/Caskroom/blender/2.82/blender.wrapper.sh
==> Existing metadata is: ''
/bin/chmod -- u\+rw /usr/local/Caskroom/blender/2.82/blender.wrapper.sh /usr/local/Caskroom/blender/2.82/blender.wrapper.sh
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames \(\"blender\"\) /usr/local/Caskroom/blender/2.82/blender.wrapper.sh
🍺  blender was successfully installed!

```

#### Output of `brew cask doctor`

```
brew cask doctor
==> Homebrew Version
2.2.6-65-g955947c
==> macOS
10.15.3
==> SIP
Enabled
==> Java
N/A
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3536 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (145 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.38.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-0.80.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.9.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/rdiscount-2.2.0.1
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-2.7.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-2.31.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.19.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.10.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/nokogiri-1.10.8
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-3.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2019.1009/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/jaro_winkler-1.5.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/jaro_winkler-1.5.4
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/unf_ext-0.0.7.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coveralls-0.8.23/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/term-ansicolor-1.7.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tins-1.24.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../../../../../../../../Library/Ruby/Gems/2.6.0/gems/sync-0.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.16.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/json-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/json-2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.2.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.2.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin19
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"

```

#### Output of `brew tap`

```
 brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/core

```

**Comment by vitorgalvao** [comment] 2020-02-27 18:25
Does it work with `brew cask install --no-quarantine blender`?

**Comment by Jarli01** [comment] 2020-02-27 19:39
Same result. 

I'm assuming the `--no-quarantine` option simply removes `com.apple.quarantine` xattr from the app? In any scenario I already remove those flags so we aren't nagged with "This app was downloaded from the internet, are you sure you want to run it"

**Comment by vitorgalvao** [comment] 2020-02-27 19:54
> I'm assuming the `--no-quarantine` option simply removes `com.apple.quarantine` xattr from the app?

No. Rather, it doesn’t add them, which is different. Adding the flag is a possible source of trouble.

Considering the popularity of this cask, that I can’t reproduce, and that you’re the only report so far, I highly suspect the issue to be on your side.

We’ll need further reports / clues before looking further into it.

**Comment by Jarli01** [comment] 2020-02-27 20:10
What else can I provide to help troubleshoot this?

**Comment by vitorgalvao** [comment] 2020-02-27 22:07
> What else can I provide to help troubleshoot this?

I don’t know, because I don’t know where the problem is. Either we get more reports and try to figure out what they all have in common, or you’re doing something particular (that you may have forgotten about, even), in which case we can’t guess.

Any tips you can give are whatever you do on your machine that might be considered out of the ordinary.

**Comment by Jarli01** [comment] 2020-02-28 13:38
My setup is pretty straightforward. 

I have a custom sudoers file in /etc/sudoers.d/ so I can remotely update without needing to have a dedicated connection to each. (Yes my sudoers file is correct)

Besides that, domain connected, with domain users. The local administrative account has full access to make any changes.

**Comment by core-code** [comment] 2020-03-10 21:11
just FYI i've tried reproducing the issue (on Catalina) but was unable to do so - Blender appeared just fine in the apps folder

**Comment by Jarli01** [comment] 2020-03-11 12:06
Hrm, I'll keep testing on my end and see if this continues for whatever else  might cause this. .

**Comment by vitorgalvao** [comment] 2020-03-13 15:54
No further reports on this, and it’s a popular cask, so closing.

**Closed by vitorgalvao** 2020-03-13 15:54 UTC
