### ISSUE TITLE
Can't uninstall 1Clipboard while its running

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-cask#51945] opened 2018-09-14 14:14 UTC
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I checked there are no [open issues](https://github.com/Homebrew/homebrew-cask/issues) for the same problem.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Can't uninstall 1Clipboard app.

#### Command that failed

```
brew cask uninstall 1clipboard
```

#### Output of command with `--force --verbose --debug`

```
brew cask uninstall 1clipboard --force --debug --verbose
==> Uninstalling Cask 1clipboard
==> Uninstalling Cask 1clipboard
==> Un-installing artifacts
==> 3 artifact/s defined
#<SortedSet:0x0000000101288208>
==> Un-installing artifact of class Cask::Artifact::Uninstall
==> Running uninstall process for 1clipboard; your password may be necessary
==> Quitting application ID com.ngwin.1clipboard
/bin/launchctl list
/usr/bin/sudo -E -- /usr/bin/osascript -e tell\ application\ id\ \"com.ngwin.1clipboard\"\ to\ quit
2018-09-14 17:09:58.417 osascript[1496:14503] GetInputSourceEnabledPrefs user file path = /Users/yurikoles/Library/Preferences/com.apple.HIToolbox.plist
2018-09-14 17:09:58.417 osascript[1496:14503] GetInputSourceEnabledPrefs effective user id path = 0
2018-09-14 17:09:58.418 osascript[1496:14503] GetInputSourceEnabledPrefs user pref content = <CFBasicHash 0x7fdc75f190f0 [0x7fff834918e0]>{type = immutable dict, count = 4,
entries =>
	0 : <CFString 0x7fff835216a8 [0x7fff834918e0]>{contents = "AppleSelectedInputSources"} = <CFArray 0x7fdc75f18620 [0x7fff834918e0]>{type = immutable, count = 2, values = (
	0 : <CFBasicHash 0x7fdc75f172d0 [0x7fff834918e0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fdc75f17270 [0x7fff834918e0]>{contents = "Non Keyboard Input Method"}
	1 : Bundle ID = <CFString 0x7fdc75f172a0 [0x7fff834918e0]>{contents = "com.apple.PressAndHold"}
}

	1 : <CFBasicHash 0x7fdc75f17310 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = <CFString 0x7fff835341e8 [0x7fff834918e0]>{contents = "Unicode Hex Input"}
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0xa4466a33d01926e9 [0x7fff834918e0]>{value = -1, type = kCFNumberSInt64Type}
}

)}
	1 : <CFString 0x7fff83502748 [0x7fff834918e0]>{contents = "AppleEnabledInputSources"} = <CFArray 0x7fdc75f18ed0 [0x7fff834918e0]>{type = immutable, count = 6, values = (
	0 : <CFBasicHash 0x7fdc75f18660 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = <CFString 0x7fff835341e8 [0x7fff834918e0]>{contents = "Unicode Hex Input"}
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0xa4466a33d01926e9 [0x7fff834918e0]>{value = -1, type = kCFNumberSInt64Type}
}

	1 : <CFBasicHash 0x7fdc75f186e0 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = Russian
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5bb995cc2faad9e9 [0x7fff834918e0]>{value = +19456, type = kCFNumberSInt64Type}
}

	2 : <CFBasicHash 0x7fdc75f18760 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = Ukrainian
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5bb995cc2faae7e9 [0x7fff834918e0]>{value = +19518, type = kCFNumberSInt64Type}
}

	3 : <CFBasicHash 0x7fdc75f18c90 [0x7fff834918e0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fdc75f18c60 [0x7fff834918e0]>{contents = "Non Keyboard Input Method"}
	1 : Bundle ID = <CFString 0x7fff8356ad48 [0x7fff834918e0]>{contents = "com.apple.CharacterPaletteIM"}
}

	4 : <CFBasicHash 0x7fdc75f18d70 [0x7fff834918e0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fdc75f18d10 [0x7fff834918e0]>{contents = "Non Keyboard Input Method"}
	1 : Bundle ID = <CFString 0x7fdc75f18d40 [0x7fff834918e0]>{contents = "com.apple.KeyboardViewer"}
}

	5 : <CFBasicHash 0x7fdc75f18e50 [0x7fff834918e0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fdc75f18df0 [0x7fff834918e0]>{contents = "Non Keyboard Input Method"}
	1 : Bundle ID = <CFString 0x7fdc75f18e20 [0x7fff834918e0]>{contents = "com.apple.PressAndHold"}
}

)}
	2 : <CFString 0x7fdc75f17240 [0x7fff834918e0]>{contents = "AppleInputSourceHistory"} = <CFArray 0x7fdc75f170e0 [0x7fff834918e0]>{type = immutable, count = 3, values = (
	0 : <CFBasicHash 0x7fdc75f18f30 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = <CFString 0x7fff835341e8 [0x7fff834918e0]>{contents = "Unicode Hex Input"}
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0xa4466a33d01926e9 [0x7fff834918e0]>{value = -1, type = kCFNumberSInt64Type}
}

	1 : <CFBasicHash 0x7fdc75f18fb0 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = Ukrainian
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5bb995cc2faae7e9 [0x7fff834918e0]>{value = +19518, type = kCFNumberSInt64Type}
}

	2 : <CFBasicHash 0x7fdc75f19030 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = Russian
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5bb995cc2faad9e9 [0x7fff834918e0]>{value = +19456, type = kCFNumberSInt64Type}
}

)}
	5 : <CFString 0x7fff83573da8 [0x7fff834918e0]>{contents = "AppleCurrentKeyboardLayoutInputSourceID"} = <CFString 0x7fdc75f190b0 [0x7fff834918e0]>{contents = "com.apple.keylayout.UnicodeHexInput"}
}
46:50: execution error: 1Clipboard отримав помилку: Скасовано користувачем. (-128)
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/osascript -e tell\ application\ id\ \"com.ngwin.1clipboard\"\ to\ quit` exited with 1. Here's the output:
2018-09-14 17:09:58.417 osascript[1496:14503] GetInputSourceEnabledPrefs user file path = /Users/yurikoles/Library/Preferences/com.apple.HIToolbox.plist
2018-09-14 17:09:58.417 osascript[1496:14503] GetInputSourceEnabledPrefs effective user id path = 0
2018-09-14 17:09:58.418 osascript[1496:14503] GetInputSourceEnabledPrefs user pref content = <CFBasicHash 0x7fdc75f190f0 [0x7fff834918e0]>{type = immutable dict, count = 4,
entries =>
	0 : <CFString 0x7fff835216a8 [0x7fff834918e0]>{contents = "AppleSelectedInputSources"} = <CFArray 0x7fdc75f18620 [0x7fff834918e0]>{type = immutable, count = 2, values = (
	0 : <CFBasicHash 0x7fdc75f172d0 [0x7fff834918e0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fdc75f17270 [0x7fff834918e0]>{contents = "Non Keyboard Input Method"}
	1 : Bundle ID = <CFString 0x7fdc75f172a0 [0x7fff834918e0]>{contents = "com.apple.PressAndHold"}
}

	1 : <CFBasicHash 0x7fdc75f17310 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = <CFString 0x7fff835341e8 [0x7fff834918e0]>{contents = "Unicode Hex Input"}
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0xa4466a33d01926e9 [0x7fff834918e0]>{value = -1, type = kCFNumberSInt64Type}
}

)}
	1 : <CFString 0x7fff83502748 [0x7fff834918e0]>{contents = "AppleEnabledInputSources"} = <CFArray 0x7fdc75f18ed0 [0x7fff834918e0]>{type = immutable, count = 6, values = (
	0 : <CFBasicHash 0x7fdc75f18660 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = <CFString 0x7fff835341e8 [0x7fff834918e0]>{contents = "Unicode Hex Input"}
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0xa4466a33d01926e9 [0x7fff834918e0]>{value = -1, type = kCFNumberSInt64Type}
}

	1 : <CFBasicHash 0x7fdc75f186e0 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = Russian
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5bb995cc2faad9e9 [0x7fff834918e0]>{value = +19456, type = kCFNumberSInt64Type}
}

	2 : <CFBasicHash 0x7fdc75f18760 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = Ukrainian
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5bb995cc2faae7e9 [0x7fff834918e0]>{value = +19518, type = kCFNumberSInt64Type}
}

	3 : <CFBasicHash 0x7fdc75f18c90 [0x7fff834918e0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fdc75f18c60 [0x7fff834918e0]>{contents = "Non Keyboard Input Method"}
	1 : Bundle ID = <CFString 0x7fff8356ad48 [0x7fff834918e0]>{contents = "com.apple.CharacterPaletteIM"}
}

	4 : <CFBasicHash 0x7fdc75f18d70 [0x7fff834918e0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fdc75f18d10 [0x7fff834918e0]>{contents = "Non Keyboard Input Method"}
	1 : Bundle ID = <CFString 0x7fdc75f18d40 [0x7fff834918e0]>{contents = "com.apple.KeyboardViewer"}
}

	5 : <CFBasicHash 0x7fdc75f18e50 [0x7fff834918e0]>{type = immutable dict, count = 2,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fdc75f18df0 [0x7fff834918e0]>{contents = "Non Keyboard Input Method"}
	1 : Bundle ID = <CFString 0x7fdc75f18e20 [0x7fff834918e0]>{contents = "com.apple.PressAndHold"}
}

)}
	2 : <CFString 0x7fdc75f17240 [0x7fff834918e0]>{contents = "AppleInputSourceHistory"} = <CFArray 0x7fdc75f170e0 [0x7fff834918e0]>{type = immutable, count = 3, values = (
	0 : <CFBasicHash 0x7fdc75f18f30 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = <CFString 0x7fff835341e8 [0x7fff834918e0]>{contents = "Unicode Hex Input"}
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0xa4466a33d01926e9 [0x7fff834918e0]>{value = -1, type = kCFNumberSInt64Type}
}

	1 : <CFBasicHash 0x7fdc75f18fb0 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = Ukrainian
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5bb995cc2faae7e9 [0x7fff834918e0]>{value = +19518, type = kCFNumberSInt64Type}
}

	2 : <CFBasicHash 0x7fdc75f19030 [0x7fff834918e0]>{type = immutable dict, count = 3,
entries =>
	0 : <CFString 0x7fff834fff68 [0x7fff834918e0]>{contents = "InputSourceKind"} = <CFString 0x7fff835454a8 [0x7fff834918e0]>{contents = "Keyboard Layout"}
	1 : <CFString 0x7fff834fac68 [0x7fff834918e0]>{contents = "KeyboardLayout Name"} = Russian
	2 : <CFString 0x7fff835315e8 [0x7fff834918e0]>{contents = "KeyboardLayout ID"} = <CFNumber 0x5bb995cc2faad9e9 [0x7fff834918e0]>{value = +19456, type = kCFNumberSInt64Type}
}

)}
	5 : <CFString 0x7fff83573da8 [0x7fff834918e0]>{contents = "AppleCurrentKeyboardLayoutInputSourceID"} = <CFString 0x7fdc75f190b0 [0x7fff834918e0]>{contents = "com.apple.keylayout.UnicodeHexInput"}
}
46:50: execution error: 1Clipboard отримав помилку: Скасовано користувачем. (-128)


Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:101:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:46:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:23:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:27:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:125:in `block in uninstall_quit'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:122:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:122:in `uninstall_quit'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:58:in `block in dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:55:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:55:in `dispatch_uninstall_directives'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:7:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:484:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:481:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:434:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:12:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:166:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
1.7.4-50-g76b41ba
==> macOS
10.14
==> SIP
Enabled (custom configuration)

configuration:
apple internal: disabled
kext signing: disabled
filesystem protections: disabled
debugging restrictions: disabled
dtrace restrictions: disabled
nvram protections: disabled
basesystem verification: disabled
==> Java
10.0.2
==> Gatekeeper support
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'
        uuid_string_t   ext_jnl_uuid;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: note: while building module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
#include <sys/types.h>
         ^
<module-includes>:353:9: note: in file included from <module-includes>:353:
#import "hfs/hfs_format.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'; did you mean 'uuid_variant'?
        char            reserved[JIB_RESERVED_SIZE];
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                            ^
/usr/local/include/uuid/uuid.h:112:12: note: 'uuid_variant' declared here
extern int uuid_variant(const uuid_t uu);
           ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreFoundation.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: error: could not build module 'Darwin'
#include <sys/types.h>
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "dispatch.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:10: note: while building module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
#include <dispatch/dispatch.h>
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:10: note: while building module 'os_object' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/dispatch/dispatch.h:48:
#include <os/object.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "os/object.h"
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/os/object.h:25:10: error: could not build module 'Darwin'
#include <Availability.h>
         ^
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4053 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (196 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-eid (11 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
/usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles (5 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```

#### Output of `brew tap`

```
buo/cask-upgrade
homebrew/bundle
homebrew/cask
homebrew/cask-drivers
homebrew/cask-eid
homebrew/cask-fonts
homebrew/cask-versions
homebrew/command-not-found
homebrew/core
homebrew/livecheck
homebrew/services
jeffreywildman/virt-manager
kde-mac/kde
theseal/ssh-askpass
vitorgalvao/tiny-scripts
yurikoles/yurikoles
```

`отримав помилку: Скасовано користувачем.` = `got error: Canceled by user`

**Comment by vitorgalvao** [comment] 2018-09-14 15:08
Try replacing the `quit` in the cask with a stronger [`signal:`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md#uninstall-key-signal). Does it work?

**Comment by yurikoles** [comment] 2018-09-14 15:37
I already quit and uninstall it, but can't reinstall due to #51958

**Comment by yurikoles** [comment] 2018-09-14 15:56
@vitorgalvao no signal signal does work.
BTW, there is issue in style/audit, they doesn't report that signals must be in subarray, I will report it.

**Comment by yurikoles** [comment] 2018-09-14 16:01
https://github.com/Homebrew/rubocop-cask/issues/66

**Comment by vitorgalvao** [comment] 2018-09-14 21:13
I’ve tried this on a VM and it worked well. Seeing as AppleScript seems to be the cause of the issue in your case, I’m closing this one in favour of https://github.com/Homebrew/homebrew-cask/issues/19076 which is already tracking the problem.

Thank you for the report.

**Closed by vitorgalvao** 2018-09-14 21:13 UTC
